</$objtype/mkfile

APEXPROOT=../../../..

#	ptyfs\	# for X11, not going to bother
TARG=\
	stty\
	tar\
	cc\

BIN=$APEXPROOT/$objtype/bin/ape
<$APEXPROOT/sys/src/cmd/mkmany

# pcc: same binary as cc; argv[0]=="pcc" selects .$O object extension
$BIN/pcc:	$BIN/cc
	cp $BIN/cc $BIN/pcc

install:V:	$BIN/cc $BIN/pcc
