APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libdwarf.a\
	$APEXPROOT/$objtype/lib/ape/libzstd.a

TARG=adeb
BIN=$APEXPROOT/$objtype/bin/ape

OFILES=\
	main.$O\
	dwarf_engine.$O\

<$APEXPROOT/sys/src/cmd/mkone

CC=pcc
CFLAGS= -c

%.$O: %.c
	$CC $CFLAGS $stem.c
