APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a
OFILES=\
	getgrent.$O\
	getgrgid.$O\
	getgrnam.$O\
	getpwent.$O\
	getpwnam.$O\
	getpwuid.$O\
	getpw_r.$O\
#	getpw_a.$O

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -I../include -D_POSIX_SOURCE -D_PLAN9_SOURCE
