APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

# split malloc into malloc, free and realloc

OFILES=\
	calloc.$O\
	malloc.$O\
	free.$O\
	realloc.$O\
	setmalloctag.$O\
	setrealloctag.$O\
# claude ported from musl\
	posix_memalign.$O\
# musl - rewrite to fit APExp?\
#	reallocarray.$O\
#	memalign.$O\
#	aligned_alloc.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE -D_PLAN9_SOURCE -I../include
