APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
	calloc.$O\
	malloc.$O\
	setmalloctag.$O\
	setrealloctag.$O\
# claude ported from musl\
	posix_memalign.$O\
# musl\
	reallocarray.$O\
	memalign.$O\
	aligned_alloc.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE -D_PLAN9_SOURCE -I../include
