/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if the `closedir' function returns void instead of `int'. */
/* #undef CLOSEDIR_VOID */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

#include "/sys/include/ape/config.h"

/* Use high resolution file timestamps if nonzero. */
#define FILE_TIMESTAMP_HI_RES 0

/* Define to 1 if the `getloadavg' function needs to be run setuid or setgid.
   */
#undef GETLOADAVG_PRIVILEGED

/* Name of package */
#define PACKAGE "make"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bug-make@gnu.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "GNU make"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "GNU make 3.82"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "gmake"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.82"

/* Define to the name of the SCCS 'get' command. */
#define SCCS_GET "get"

/* Version number of package */
#define VERSION "3.82"

typedef unsigned long long uintmax_t;
#define NO_ARCHIVES

