APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libsec.a
FILES=\
	chachablock\
	md5block\
	sha1block\
	aesni\

HFILES=$APEXPROOT/sys/include/ape/libsec.h

SFILES=${FILES:%=%.s}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

<$APEXPROOT/sys/src/cmd/mksyslib

%.$O:	%.s
	$AS $AFLAGS $stem.s
