</$objtype/mkfile
APEXPROOT=../../../../..
PTCHSRC=$APEXPROOT/sys/src/external/patch

TARG=patch

OFILES=\
	inp.$O patch.$O pch.$O \
	safe.$O util.$O version.$O merge.$O

BIN=$APEXPROOT/$objtype/bin/ape

<$APEXPROOT/sys/src/cmd/mkone

CC=pcc -c
CFLAGS=-B -p -D_POSIX_SOURCE \
	-D_BSD_EXTENSION -I$PTCHSRC \
	-I$PTCHSRC/src -I$PTCHSRC/lib \
	-DHAVE_CONFIG_H \
	-Ded_PROGRAM="/bin/ed"

%.$O: $PTCHSRC/src/%.c
	$CC $CFLAGS $prereq

%.$O: $PTCHSRC/lib/%.c
	$CC $CFLAGS $prereq



