</$objtype/mkfile

TARG=9l
OFILES=\
	asm.$O\
	asmout.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	cnam.$O\
	sched.$O\
	compat.$O\

HFILES=\
	l.h\
	../9c/9.out.h\
	../cc/compat.h\

APEXPROOT=../../../..
BIN=$APEXPROOT/$objtype/bin
<$APEXPROOT/sys/src/cmd/mkone

../9c/enam.c: ../9c/9.out.h
	@ { cd ../9c; mk enam.c }

enam.$O:	../9c/enam.c
	$CC $CFLAGS ../9c/enam.c

cnam.c:	l.h
	rc mkcname

compat.$O:	../cc/compat
