</$objtype/mkfile
APEXPROOT=../../../../../..
LIB=$APEXPROOT/$objtype/lib/ape/libfl.a


OFILES=	libmain.$O\
		libyywrap.$O 

<$APEXPROOT/sys/src/cmd/mksyslib

FLEXSRC=../../../../external/flex

%.$O: $FLEXSRC/src/%.c
	$CC $CFLAGS $FLEXSRC/src/$stem.c

CC=pcc
LD=pcc
CFLAGS=-c 

nuke:V:
	mk clean
	rm -f $LIB
