</$objtype/mkfile
APEXPROOT=../../../../..

TARG=bison

OFILES=\
	bison-AnnotationList.$O \
	bison-InadequacyList.$O \
	bison-Sbitset.$O \
	bison-assoc.$O \
	bison-closure.$O \
	bison-complain.$O \
	bison-conflicts.$O \
	bison-counterexample.$O \
	bison-derivation.$O \
	bison-derives.$O \
	bison-files.$O \
	bison-fixits.$O \
	bison-getargs.$O \
	bison-glyphs.$O \
	bison-gram.$O \
	bison-graphviz.$O \
	bison-ielr.$O \
	bison-lalr.$O \
	bison-location.$O \
	bison-lr0.$O \
	bison-lssi.$O \
	bison-main.$O \
	bison-muscle-tab.$O \
	bison-named-ref.$O \
	bison-nullable.$O \
	bison-output.$O \
	bison-parse-gram.$O \
	bison-parse-simulation.$O \
	bison-print-graph.$O \
	bison-print-xml.$O \
	bison-print.$O \
	bison-reader.$O \
	bison-reduce.$O \
	bison-relation.$O \
	bison-scan-code-c.$O \
	bison-scan-gram-c.$O \
	bison-scan-skel-c.$O \
	bison-state.$O \
	bison-state-item.$O \
	bison-strversion.$O \
	bison-symlist.$O \
	bison-symtab.$O \
	bison-tables.$O \
	bison-uniqstr.$O

LIB_OBJS=\
	liby_a-main.$O \
	liby_a-yyerror.$O

LIB=libbison.a$O ../gnulib/libgnu.a$O

BIN=$APEXPROOT/$objtype/bin/ape

<$APEXPROOT/sys/src/cmd/mkone

BISONSRC=../../../external/bison

#during building from scratch, the new pcc is not picked up and compilation
#fails on include_next
CC=$APEXPROOT/$objtype/bin/pcc

CFLAGS=-c -I. -I$BISONSRC -I$BISONSRC/lib -I$BISONSRC/src\
		-B -DHAVE_CONFIG_H\
		-DLOCALEDIR="/sys/lib/ape/locale"

CLEANFILES=$LIB

bison-%.$O: $BISONSRC/src/%.c
	$CC $CFLAGS -c $prereq -o $target

%.$O: $BISONSRC/lib/%.c
	$CC $CFLAGS $prereq -o $target

%.$O: $BISONSRC/lib/bitset/%.c
	$CC $CFLAGS $prereq -o $target

%.$O: $BISONSRC/lib/malloc/%.c
	$CC $CFLAGS $prereq -o $target

%.$O: $BISONSRC/lib/unistr/%.c
	$CC $CFLAGS $prereq -o $target

%.$O: $BISONSRC/lib/glthread/%.c
	$CC $CFLAGS $prereq -o $target

%.$O: $BISONSRC/lib/uniwidth/%.c
	$CC $CFLAGS $prereq -o $target

liby_a-%.$O: $BISONSRC/lib/%.c
	$CC $CFLAGS $prereq -o $target

libbison.a$O: $LIB_OBJS
		ar vu libbison.a$O $LIB_OBJS

install:V:
		cp $BISONSRC/doc/bison.1 $APEXPROOT/sys/man/1/bison
		cp $BISONSRC/doc/yacc.1 $APEXPROOT/sys/man/1/yacc



