APEXPROOT=../../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
# musl asm converted to plan9\
	acosl.$O\
	asinl.$O\
	atan2l.$O\
	atanl.$O\
	exp2l.$O\
	expl.$O\
	floorl.$O\
	log10l.$O\
	log1pl.$O\
	log2l.$O\
	logl.$O\


<$APEXPROOT/sys/src/cmd/mksyslib

%.$O: %.s\
    $Oa $stem.s\




