</$objtype/mkfile

PCRESRC=../../../external/pcre
DIRS=doc 

install:V:
	mk -f mkfile.libpcre $target
	mk -f mkfile.libpcreposix $target
	for (i in $DIRS)
		@{ cd $i; mk $target }
	mkdir -p /$objtype/lib/ape/pkgconfig
	cp $PCRESRC/libpcre.pc  /$objtype/lib/ape/pkgconfig/
	cp $PCRESRC/libpcreposix.pc  /$objtype/lib/ape/pkgconfig/
	chmod +x $PCRESRC/pcre-config
	cp $PCRESRC/pcre-config /rc/bin/ape

installall:V:
	mk -f mkfile.libpcre install
	mk -f mkfile.libpcreposix install
	for (i in $DIRS)
		@{ cd $i; mk install }
	mkdir -p /$objtype/lib/ape/pkgconfig
	cp $PCRESRC/libpcre.pc  /$objtype/lib/ape/pkgconfig/
	cp $PCRESRC/libpcreposix.pc  /$objtype/lib/ape/pkgconfig/
	chmod +x $PCRESRC/pcre-config
	cp $PCRESRC/pcre-config /rc/bin/ape

clean:V:
	mk -f mkfile.libpcre $target
	mk -f mkfile.libpcreposix $target
	mk -f mkfile.pcretest $target
	for (i in $DIRS)
		@{ cd $i; mk $target }

nuke:V:
	mk -f mkfile.libpcre $target
	mk -f mkfile.libpcreposix $target
	mk -f mkfile.pcretest $target
	for (i in $DIRS)
		@{ cd $i; mk $target }
	rm -f /$objtype/lib/ape/pkgconfig/libpcre.pc
	rm -f /$objtype/lib/ape/pkgconfig/libpcreposix.pc
	rm -f /rc/bin/ape/pcre-config

test:V:
	mk -f mkfile.pcretest