</$objtype/mkfile

APEXPROOT=../../../..
CXXSRC=../../external/c++

CFLAGS=-c -B -DDEM_MAIN -D_POSIX_SOURCE -D_BSD_EXTENSION -I$CXXSRC/demangle 
CC=pcc
TARG=c++filt
OFILES=dem.$O
BIN=$APEXPROOT/$objtype/bin/c++

</sys/src/cmd/mkone

dem.$O:	$CXXSRC/demangle/dem.c
		$CC $CFLAGS $CXXSRC/demangle/dem.c

