
#
# Portable Object Compiler
# $Id: Makefile.nmk,v 1.3 2003/10/12 10:01:34 stes Exp $
#

#
# This Makefile should work with Microsoft nmake
#

.SILENT:

MKDIR=mkdir
OBJC=objc
RM=del
CP=copy
AR=lib /NOLOGO
FINAL_AR=echo
RANLIB=echo
MAKE=nmake
DBG_MFLAGS=-q -g
OPT_MFLAGS=-q -O -DNDEBUG
OBJSUFFIX=obj
LIBSUFFIX=lib
BOOTDIR=..\..
LIBDIR=$(BOOTDIR)\lib
BINDIR=$(BOOTDIR)\bin
IFLAGS=-noI -I..\..\include\objcrt
MFLAGS=$(OPT_MFLAGS)
DLLOBJSDIR=dll

.SUFFIXES: .m

DLL=objpak.dll
LIBRARY=objpak.lib
IMPLIB=objpak_s.lib

OBJFILES=\
	ascfiler.obj\
	  notfound.obj\
	  outofbnd.obj\
	  badvers.obj\
	  typeinc.obj\
	  unknownt.obj\
	cltn.obj\
	  ordcltn.obj\
	  sortcltn.obj\
	  set.obj\
	  bag.obj\
	  stack.obj\
	  runarray.obj\
        dictnary.obj\
	sequence.obj\
	array.obj\
	  idarray.obj\
	  intarray.obj\
	  ocstring.obj\
	rectangl.obj\
	point.obj\
	assoc.obj\
	objgraph.obj\
	cltnseq.obj\
	keyseq.obj\
	valueseq.obj\
	setseq.obj\
	bagseq.obj\
	txtattr.obj\
	octext.obj\
	txtstyle.obj\
	paragrph.obj\
	treeseq.obj

.m.obj:
	$(OBJC) -c $*.m $(MFLAGS) $(IFLAGS)

ALL :	$(LIBRARY)

$(LIBRARY) : $(OBJFILES)
	$(AR) /OUT:$(LIBRARY) $(OBJFILES)
	$(RANLIB) $(LIBRARY)

bootstrap :
	-$(MKDIR) $(LIBDIR)
	-$(MKDIR) $(BINDIR)
	-$(CP) $(LIBRARY) $(LIBDIR)

cleantmp :
	-$(RM) *.P
	-$(RM) *.c
	-$(RM) *.i

clean : cleantmp
	-$(RM) *.obj
	-$(RM) *.lib

distclean : clean
	-$(RM) Makefile 
	-$(RM) config.h 

