#!/usr/bin/env python3
"""
apehdr-sweep -- can each header in sys/include/ape be included ALONE?

    python3 sys/lib/tests/apehdr-sweep.py          # from the repo root

Third host SWEEP in this directory, after `apdecl-sweep.py` (missing
prototypes in libap) and `strerror-xcheck.py` (the errno table).

------------------------------------------------------------------
WHY IT EXISTS: TWO BUGS IN ONE SESSION, NEITHER FOUND BY A BUILD.

A header is only exercised by whatever happens to include it, so a
header that is broken for everyone else compiles fine for the tree
that ships it. Both of these shipped:

  * `tcl.h' was installed ALONE and its line 2433 is
    `#include "tclDecls.h"', which was not installed at all. So
    `#include <tcl.h>' from anything outside Tcl's own build had
    always been a fatal error on the first line -- the `#pragma lib'
    in it was never once reached. Nothing in the tree noticed,
    because Tcl's own build puts `-I$TCLSRC/generic' first.

  * `qlock.h' carried a SECOND `typedef struct { int val; } Lock;'
    beside the one it already got from `<lock.h>', guarded with
    `#ifndef Lock'. **Lock is a typedef, not a macro**, so that test
    is always true and the duplicate was always emitted. Two
    anonymous structs are distinct types, so it is a constraint
    violation; gcc refuses, and `<pthread.h>' includes both files, so
    SIXTEEN of the 149 headers here could not be compiled by a
    standards-strict compiler. kencc tolerated it, which is exactly
    why it survived.

A third, mine, would also have been caught in one run: a comment
added to `<termios.h>' contained a star followed by a slash, closed
itself mid-sentence, and broke every translation unit that includes
it. I shipped it without compiling the header once.

------------------------------------------------------------------
WHAT IT MEASURES, AND WHAT IT CANNOT.

For each `sys/include/ape/*.h' it compiles a file whose entire
content is `#include <that header>'. The include path is the BUILD's,
in the build's ORDER -- `$objtype/include/ape' BEFORE
`sys/include/ape', which is a documented invariant of this tree and
not a detail: flattening the two into one directory made the first
version of this sweep report 16 false `Lock' conflicts of its own
making. *An instrument whose include path is not the build's include
path is measuring a different program*, which is the lesson
`apdecl-sweep` learned the same way.

The two trees are STAGED into a scratch directory first, because
several arch headers reach their counterpart through an ABSOLUTE
`#include "/sys/include/ape/..."' that does not exist on the build
host. The staging rewrites those to relative; it is the same
workaround `readdir.c`'s gcc check needed.

**It is gcc, not kencc, so some failures are the HOST's and not the
tree's.** Those are listed in EXPECTED below with the reason, and the
sweep reports only what is NOT on that list. The largest group is
`bool`: kencc has it as a C23 keyword and gcc in C mode does not, so
four headers that are perfectly fine under pcc fail here. *Reporting
them would make the sweep unreadable, and suppressing them silently
would make it dishonest* -- it prints the expected count too.

It is a LOWER BOUND. A header that compiles alone can still be wrong:
this asks whether the include closure is complete and the syntax is
valid, not whether anything it declares is correct.
"""

import os, re, shutil, subprocess, sys, tempfile

# header -> why it is not expected to compile standalone on the HOST.
# Anything not in here that fails is a finding.
EXPECTED = {
    # Plan 9 extension headers: they need <u.h> first, by design, and
    # `This' is u.h's. Including them bare is not how they are used.
    "ar.h": "needs <u.h> first (Plan 9 extension header)",
    "auth.h": "needs <u.h> first",
    "bio.h": "needs <u.h> first",
    "cursor.h": "needs <u.h> first",
    "draw.h": "needs <u.h> first",
    "event.h": "needs <u.h> first",
    "keyboard.h": "needs <u.h> first",
    "libsec.h": "needs <u.h> first",
    "mouse.h": "needs <u.h> first",
    "plumb.h": "needs <u.h> first",
    "select.h": "needs <u.h> first",
    # kencc has `bool' as a C23 keyword; gcc in C mode does not.
    # These compile under pcc. HOST ARTEFACT, not a tree bug.
    "curses.h": "uses bool, a kencc keyword gcc lacks in C mode",
    "panel.h": "uses bool, a kencc keyword gcc lacks in C mode",
    "term.h": "uses bool, a kencc keyword gcc lacks in C mode",
    "menu.h": "uses bool, a kencc keyword gcc lacks in C mode",
    "textstyle.h": "uses bool, a kencc keyword gcc lacks in C mode",
    "form.h": "uses bool, a kencc keyword gcc lacks in C mode",
    # Not standalone by design: included from their public header.
    "tclDecls.h": "internal, included from <tcl.h>",
    "tkDecls.h": "internal, included from <tk.h>",
    # Need a build-generated header or a width selected first.
    "png.h": "needs pnglibconf.h, generated by libpng's build",
    "pngconf.h": "needs pnglibconf.h, generated by libpng's build",
    "lz4file.h": "needs lz4frame_static.h",
    "pcre2.h": "requires PCRE2_CODE_UNIT_WIDTH defined first",
    "libdwarfp.h": "needs <libdwarf.h> first",
    # Small real gaps, recorded rather than fixed: they want one more
    # include of their own. Harmless because every real caller has it.
    "fts.h": "uses dev_t without <sys/types.h>",
    "dlfcn.h": "uses NULL without <stddef.h>",
}


def stage(root, dst):
    """Copy the two include trees, rewriting absolute self-includes."""
    arch, sysd = os.path.join(dst, "arch"), os.path.join(dst, "sys")
    shutil.copytree(os.path.join(root, "amd64/include/ape"), arch)
    shutil.copytree(os.path.join(root, "sys/include/ape"), sysd)
    for d in (arch, sysd):
        for dirpath, _, names in os.walk(d):
            for n in names:
                if not n.endswith((".h", ".H")):
                    continue
                f = os.path.join(dirpath, n)
                try:
                    t = open(f, encoding="utf-8", errors="replace").read()
                except OSError:
                    continue
                if '"/sys/include/ape/' in t:
                    open(f, "w", encoding="utf-8").write(
                        t.replace('"/sys/include/ape/', '"'))
    return arch, sysd


def main():
    root = os.getcwd()
    hdrdir = os.path.join(root, "sys/include/ape")
    if not os.path.isdir(hdrdir):
        sys.exit("apehdr-sweep: run me from the repo root")

    tmp = tempfile.mkdtemp(prefix="apehdr.")
    try:
        arch, sysd = stage(root, tmp)
        src = os.path.join(tmp, "probe.c")
        headers = sorted(f for f in os.listdir(hdrdir) if f.endswith(".h"))

        findings, expected_hit = [], 0
        for h in headers:
            open(src, "w").write("#include <%s>\n" % h)
            # -nostdinc: the host's own headers must not paper over a
            # gap in APE's. Without it a missing <stddef.h> is invisible.
            p = subprocess.run(
                ["gcc", "-fsyntax-only", "-nostdinc", "-I", arch, "-I", sysd, src],
                capture_output=True, text=True)
            if p.returncode == 0:
                if h in EXPECTED:
                    findings.append((h, "EXPECTED TO FAIL AND DID NOT: "
                                        + EXPECTED[h]))
                continue
            m = re.search(r"error: (.*)", p.stderr)
            msg = m.group(1).strip() if m else "(no error: line; see stderr)"
            if h in EXPECTED:
                expected_hit += 1
            else:
                findings.append((h, msg))

        # ---- the TOGETHER case: one TU including everything ----
        #
        # Compiling each header ALONE cannot see a name declared twice
        # in two different headers, because each file is fine by
        # itself and only the COMBINATION conflicts. That is not
        # hypothetical: <stdlib.h> declared `uname(struct utsname *)'
        # and `getrusage(int, struct rusage *)' without defining or
        # including either struct, so each was a fresh incomplete type
        # scoped to the declaration -- and any program including
        # <stdlib.h> and then the real header got `conflicting types'.
        # bacon is what hit it.
        #
        # A pairwise sweep is 149*148/2 compiles; including everything
        # at once is ONE, and it catches the same class. It cannot say
        # WHICH pair, but the error names the symbol and both sites.
        together = [h for h in headers if h not in EXPECTED]
        open(src, "w").write("".join("#include <%s>\n" % h for h in together))
        p = subprocess.run(
            ["gcc", "-fsyntax-only", "-nostdinc", "-I", arch, "-I", sysd, src],
            capture_output=True, text=True)
        tog = [l for l in p.stderr.splitlines() if " error: " in l]

        print("apehdr-sweep: %d headers, %d known-not-standalone (see "
              "EXPECTED), %d findings" % (len(headers), expected_hit,
                                          len(findings)))
        print("apehdr-sweep: all %d together in one translation unit: %d "
              "errors" % (len(together), len(tog)))
        for l in tog[:14]:
            print("  " + l.split(" error: ", 1)[1][:70])

        # TRIAGED -- and TWELVE ERRORS ARE SIX CAUSES, which is the
        # whole reason to triage rather than count. Still NOT added to
        # `findings', so it does not gate: three of the six are design
        # intent, and a sweep that failed on those would cry wolf.
        #
        #  f2c.h           FIVE of the twelve, and one header.
        #                  `#define min/max/abs' (159-162) collide with
        #                  <libv.h>'s `extern int min(int,int)', and
        #                  `typedef struct {real r,i;} complex' (18)
        #                  collides with <complex.h>'s
        #                  `#define complex _Complex'. *A transpiler's
        #                  private runtime header, installed public,
        #                  owning four names two C standard headers
        #                  own.* 149 files include it and every one is
        #                  under external/f2c. RECOMMENDATION: it does
        #                  not belong in sys/include/ape.
        #
        #  regex.h /       THREE, and DESIGN INTENT. pcre2posix spells
        #  pcre2posix.h    the REG_* codes as an ENUM where regex.h
        #                  `#define's them, so regex.h:44 turns
        #                  pcre2posix's enumerator into a numeric
        #                  constant; the regex_t/regmatch_t pair is the
        #                  same collision. They are ALTERNATIVES and no
        #                  program includes both.
        #
        #  Plan9libnet.h   TWO, and the tree already fixed it once.
        #                  It declares Plan 9's `accept(int, char*)'
        #                  and `listen(char*, char*)' -- different
        #                  functions wearing POSIX's names -- against
        #                  <sys/socket.h>. **<libnet.h> beside it is
        #                  the same interface with `net_' prefixes,
        #                  and is what all five callers in the tree
        #                  use.** Nothing includes Plan9libnet.h at
        #                  all. RECOMMENDATION: delete it; a header
        #                  that cannot be combined with <sys/socket.h>
        #                  and that nothing includes is only a trap.
        #
        #  bsd.h:47        ONE, REAL, and OURS. `getopt(int, char**,
        #                  char*)' where POSIX says `(int, char *const
        #                  *, const char *)' -- and **<unistd.h> does
        #                  not declare getopt at all**, so this is the
        #                  tree's only declaration and it is the wrong
        #                  one. bsd.h is reached from <stdlib.h>,
        #                  <string.h>, <strings.h>, <unistd.h> and
        #                  <alltypes.h>.
        #
        #  features.h:55   ONE, REAL, OURS, and it HAS A VICTIM.
        #                  `#define hidden' is musl's internal
        #                  visibility macro, in a PUBLIC header reached
        #                  from <byteswap.h>, <endian.h>, <ftw.h>,
        #                  <glob.h>, <iconv.h> and more -- and
        #                  `sqlite3.h:10957' declares `unsigned char
        #                  hidden[48];', which is ERASED wherever
        #                  features.h was included first. *A silent
        #                  struct-layout change in a public API.*
        #                  `weak_alias' (51) is the same shape with no
        #                  victim found yet.
        #                  RECOMMENDATION, and it needs care: libap's
        #                  own `multibyte/internal.c:25' already does
        #                  `#ifndef hidden / #define hidden' for
        #                  itself, so the private users can carry their
        #                  own -- but others (`network/lookup.h:46')
        #                  rely on the leak, which is the
        #                  <stdio.h>-leaked-errno shape. Sweep libap
        #                  before removing it from the public header.
        #
        # Six causes, and only two of them are bugs in this tree.
        for h, msg in findings:
            print("  %-24s %s" % (h, msg))
        if not findings:
            print("  none -- every other header compiles on its own.")
        # An entry in EXPECTED that starts passing is reported above
        # rather than quietly dropped: a list of excuses that nobody
        # ever shortens is how a sweep stops meaning anything.
        return 1 if findings else 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
