/*
 * compound-literal-test.c -- C99 6.5.2.5 compound literals.
 *
 * The address-of cases are the point.  compoundlit() in cc/dcl.c lowers
 *
 *	(struct S){1, 2}
 *
 * to OCOMMA(init-tree, ONAME-of-hidden-temporary).  The OCOMMA is marked
 * addable only for scalar and pointer types -- struct, union and complex
 * literals are generated by sugen() rather than cgen(), and marking those
 * addable produced "unknown type in regalloc: UNION".  So &(struct S){...}
 * failed the l-value test in cc/com.c with "not an l-value".
 *
 * cc/com.c's OADDR case now rewrites &(a, b) to (a, &b) first, which puts
 * the OADDR on the temporary's ONAME, addressable whatever its type.
 *
 * Found in gnulib's randperm.c, which passes hash_remove a pointer to a
 * struct compound literal:
 *
 *	hash_remove (sv, &(struct sparse_ent_) {i, 0});
 *
 * The sizeof cases came later, from bison. An array compound literal
 * takes its size from the number of initialisers, exactly as
 * "int a[] = {1,2,3}" does, and gnulib and bison count variadic
 * arguments with that:
 *
 *	#define ARRAY_CARDINALITY(a) (sizeof (a) / sizeof (*(a)))
 *	#define UNIQSTR_CONCAT(...) \
 *	  uniqstr_concat (ARRAY_CARDINALITY (((char const *[]) {__VA_ARGS__})), \
 *	                  __VA_ARGS__)
 *
 * bison builds every muscle key that way. With the count wrong,
 * muscle_name("lr.type", "kind") returned "percent_define_" -- the first
 * fragment alone -- so every muscle collided into one entry, and
 * muscle_kind_new got an empty string and aborted with no diagnostic.
 * bison could not generate a parser at all.
 *
 * Build and run:  pcc -o compound-literal-test compound-literal-test.c
 * Prints "PASS" per case; exit status is the number of failures.
 */

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#define ARRAY_CARDINALITY(a) (sizeof (a) / sizeof (*(a)))

/* bison's UNIQSTR_CONCAT, with the same shape. */
#define CONCAT(...) \
	concat(ARRAY_CARDINALITY(((char const *[]){__VA_ARGS__})), \
	       __VA_ARGS__)

static char *
concat(int nargs, ...)
{
	static char buf[256];
	va_list ap;
	int i;

	buf[0] = 0;
	va_start(ap, nargs);
	for (i = 0; i < nargs; i++)
		strcat(buf, va_arg(ap, char const *));
	va_end(ap);
	return buf;
}

static int failures;

static void
checkd(const char *what, int ok, const char *detail)
{
	if (ok)
		printf("PASS  %s\n", what);
	else {
		printf("FAIL  %s%s%s\n", what, detail ? ": " : "",
		       detail ? detail : "");
		failures++;
	}
}

static void
check(const char *what, int ok)
{
	if (ok)
		printf("PASS  %s\n", what);
	else {
		printf("FAIL  %s\n", what);
		failures++;
	}
}

struct ent {
	unsigned long index;
	unsigned long val;
};

union u {
	int i;
	char c[4];
};

/* Takes the literal by pointer, the way gnulib's hash_remove does. */
static unsigned long
sum(const struct ent *e)
{
	return e->index + e->val;
}

/* By value, for comparison: this path always worked. */
static unsigned long
sumv(struct ent e)
{
	return e.index + e.val;
}

int
main(void)
{
	int i, j;

	i = 3;
	j = 4;

	/* The randperm.c case: address of a struct compound literal, with
	   non-constant initialisers, as a function argument. */
	check("&(struct){i,0} as argument", sum(&(struct ent){i, 0}) == 3);
	check("&(struct){j,1} as argument", sum(&(struct ent){j, 1}) == 5);

	/* Two in one expression -- randperm.c does exactly this, and the
	   two hidden temporaries must not collide. */
	check("two literals in one expression",
	      sum(&(struct ent){i, 0}) + sum(&(struct ent){j, 1}) == 8);

	/* Bound to a pointer, then used after the full expression. The
	   lifetime is the enclosing block (6.5.2.5p5), so this is valid. */
	{
		struct ent *p = &(struct ent){i, j};
		check("&(struct){...} bound to a pointer", p->index == 3 && p->val == 4);
		p->val = 9;
		check("literal through the pointer is writable", sum(p) == 12);
	}

	/* Members reached directly off the literal, no address taken. */
	check("(struct){...}.member", ((struct ent){i, j}).val == 4);

	/* By value -- the control. */
	check("(struct){...} passed by value", sumv((struct ent){i, j}) == 7);

	/* Unions take the same sugen() path as structs. */
	{
		union u *up = &(union u){0};
		up->i = 0;
		up->c[0] = 1;
		check("&(union){...}", up->i == 1 || up->c[0] == 1);
	}

	/* Arrays: the literal is an array object, so it decays to a
	   pointer to its first element like any other array.

	   &(int[]){...} is deliberately NOT tested. kencc does not give
	   &arr the type int(*)[N] for any array, named or literal -- it
	   warns "address of array/func ignored" (cc/com.c, the typeaf
	   branch of tcomo) and yields the array itself. So (*&(int[]){7,8})[1]
	   does not compile, and that is a pre-existing kencc property of
	   &array, nothing to do with compound literals. */
	{
		int *a = (int[]){10, 20, 30};
		check("(int[]){...} decays", a[0] == 10 && a[2] == 30);
	}

	/* Scalar and pointer literals -- these were already addressable,
	   and must stay that way. */
	check("&(int){i}", *&(int){i} == 3);
	{
		char *s = "abc";
		check("&(char *){s}", strcmp(*&(char *){s}, "abc") == 0);
	}

	/* Nested: a struct literal initialised from another literal's
	   members. */
	check("nested literals",
	      sum(&(struct ent){((struct ent){i, j}).val, 1}) == 5);

	/* Static storage duration: at file scope the literal is CSTATIC.
	   Here inside a function it is CAUTO, but a const-qualified one
	   still has to be addressable. */
	{
		const struct ent *cp = &(const struct ent){5, 6};
		check("&(const struct){...}", cp->index + cp->val == 11);
	}

	/*
	 * An array compound literal is sized by its initialisers, like
	 * any other array declared with an empty [].
	 */
	{
		char detail[96];

		sprintf(detail, "got %d, wanted %d",
		    (int)sizeof((char const *[]){"a", "b", "c", "d", "e"}),
		    (int)(5 * sizeof(char const *)));
		checkd("array literal sized by its initialisers",
		    sizeof((char const *[]){"a", "b", "c", "d", "e"})
		        == 5 * sizeof(char const *), detail);

		sprintf(detail, "got %d, wanted 5",
		    (int)ARRAY_CARDINALITY(((char const *[]){
		        "a", "b", "c", "d", "e"})));
		checkd("ARRAY_CARDINALITY of a 5-element literal",
		    ARRAY_CARDINALITY(((char const *[]){
		        "a", "b", "c", "d", "e"})) == 5, detail);

		sprintf(detail, "got %d, wanted 1",
		    (int)ARRAY_CARDINALITY(((char const *[]){"a"})));
		checkd("ARRAY_CARDINALITY of a 1-element literal",
		    ARRAY_CARDINALITY(((char const *[]){"a"})) == 1, detail);

		sprintf(detail, "got %d, wanted %d",
		    (int)sizeof((int[]){1, 2, 3, 4, 5, 6, 7}),
		    (int)(7 * sizeof(int)));
		checkd("int array literal sized by its initialisers",
		    sizeof((int[]){1, 2, 3, 4, 5, 6, 7}) == 7 * sizeof(int),
		    detail);
	}

	/*
	 * Storage, which is a separate question from sizeof.
	 * compoundlit() in cc/dcl.c calls adecl() -- which reserves the
	 * frame slot from t->width -- before doinit(), and it is doinit
	 * that sets the width of an array declared with an empty [].
	 * So the slot may be reserved as zero bytes and overlap the next
	 * auto. bison never sees this: it uses these literals only
	 * inside sizeof, whose operand is not evaluated.
	 */
	{
		int *p = (int[]){11, 22, 33, 44, 55};
		int guard[8];
		char detail[96];
		int i;

		for (i = 0; i < 8; i++)
			guard[i] = -1;
		sprintf(detail, "p[0]=%d p[4]=%d, wanted 11 and 55",
		    p[0], p[4]);
		checkd("array literal keeps its storage", p[0] == 11
		    && p[4] == 55 && guard[0] == -1, detail);
	}

	/*
	 * The whole idiom: count the arguments with the literal, then
	 * pass them variadically. This is bison's UNIQSTR_CONCAT, and
	 * the string below is the muscle key it failed to build.
	 */
	{
		char *r = CONCAT("percent_define_", "kind", "(", "lr.type",
		    ")");
		char detail[160];

		sprintf(detail, "got [%s]", r);
		checkd("count with a literal, then pass variadically",
		    strcmp(r, "percent_define_kind(lr.type)") == 0, detail);
	}

	if (failures)
		printf("\n%d failure(s)\n", failures);
	else
		printf("\nall ok\n");
	return failures;
}
