/*
 * compound-literal-test.c -- C99 6.5.2.5 compound literals.
 *
 * The address-of cases are the point.  compoundlit() in cc/dcl.c lowers
 *
 *	(struct S){1, 2}
 *
 * to OCOMMA(init-tree, ONAME-of-hidden-temporary).  The OCOMMA is marked
 * addable only for scalar and pointer types -- struct, union and complex
 * literals are generated by sugen() rather than cgen(), and marking those
 * addable produced "unknown type in regalloc: UNION".  So &(struct S){...}
 * failed the l-value test in cc/com.c with "not an l-value".
 *
 * cc/com.c's OADDR case now rewrites &(a, b) to (a, &b) first, which puts
 * the OADDR on the temporary's ONAME, addressable whatever its type.
 *
 * Found in gnulib's randperm.c, which passes hash_remove a pointer to a
 * struct compound literal:
 *
 *	hash_remove (sv, &(struct sparse_ent_) {i, 0});
 *
 * Build and run:  pcc -o compound-literal-test compound-literal-test.c
 * Prints "PASS" per case; exit status is the number of failures.
 */

#include <stdio.h>
#include <string.h>

static int failures;

static void
check(const char *what, int ok)
{
	if (ok)
		printf("PASS  %s\n", what);
	else {
		printf("FAIL  %s\n", what);
		failures++;
	}
}

struct ent {
	unsigned long index;
	unsigned long val;
};

union u {
	int i;
	char c[4];
};

/* Takes the literal by pointer, the way gnulib's hash_remove does. */
static unsigned long
sum(const struct ent *e)
{
	return e->index + e->val;
}

/* By value, for comparison: this path always worked. */
static unsigned long
sumv(struct ent e)
{
	return e.index + e.val;
}

int
main(void)
{
	int i, j;

	i = 3;
	j = 4;

	/* The randperm.c case: address of a struct compound literal, with
	   non-constant initialisers, as a function argument. */
	check("&(struct){i,0} as argument", sum(&(struct ent){i, 0}) == 3);
	check("&(struct){j,1} as argument", sum(&(struct ent){j, 1}) == 5);

	/* Two in one expression -- randperm.c does exactly this, and the
	   two hidden temporaries must not collide. */
	check("two literals in one expression",
	      sum(&(struct ent){i, 0}) + sum(&(struct ent){j, 1}) == 8);

	/* Bound to a pointer, then used after the full expression. The
	   lifetime is the enclosing block (6.5.2.5p5), so this is valid. */
	{
		struct ent *p = &(struct ent){i, j};
		check("&(struct){...} bound to a pointer", p->index == 3 && p->val == 4);
		p->val = 9;
		check("literal through the pointer is writable", sum(p) == 12);
	}

	/* Members reached directly off the literal, no address taken. */
	check("(struct){...}.member", ((struct ent){i, j}).val == 4);

	/* By value -- the control. */
	check("(struct){...} passed by value", sumv((struct ent){i, j}) == 7);

	/* Unions take the same sugen() path as structs. */
	{
		union u *up = &(union u){0};
		up->i = 0;
		up->c[0] = 1;
		check("&(union){...}", up->i == 1 || up->c[0] == 1);
	}

	/* Arrays: the literal is an array object, so it decays and the
	   address-of is redundant but legal. */
	{
		int *a = (int[]){10, 20, 30};
		check("(int[]){...} decays", a[0] == 10 && a[2] == 30);
		check("&(int[]){...}", (*&(int[]){7, 8})[1] == 8);
	}

	/* Scalar and pointer literals -- these were already addressable,
	   and must stay that way. */
	check("&(int){i}", *&(int){i} == 3);
	{
		char *s = "abc";
		check("&(char *){s}", strcmp(*&(char *){s}, "abc") == 0);
	}

	/* Nested: a struct literal initialised from another literal's
	   members. */
	check("nested literals",
	      sum(&(struct ent){((struct ent){i, j}).val, 1}) == 5);

	/* Static storage duration: at file scope the literal is CSTATIC.
	   Here inside a function it is CAUTO, but a const-qualified one
	   still has to be addressable. */
	{
		const struct ent *cp = &(const struct ent){5, 6};
		check("&(const struct){...}", cp->index + cp->val == 11);
	}

	if (failures)
		printf("\n%d failure(s)\n", failures);
	else
		printf("\nall ok\n");
	return failures;
}
