/*
 * ctype-xcheck -- libap's C-locale character table against glibc's,
 * every classification, all 256 values.
 *
 * A HOST PROGRAM, not a Plan 9 test. It links libap's own table into a
 * glibc program beside the reference implementation, the way
 * tz-xcheck.c does for tzone.c:
 *
 *	gcc -w -I ../../include/ape -c \
 *	    ../../src/ape/lib/ap/ctype/ctype.c -o /tmp/apectype.o
 *	gcc -Wall -o /tmp/ctype-xcheck ctype-xcheck.c /tmp/apectype.o
 *	/tmp/ctype-xcheck
 *
 * (from sys/lib/tests). **TWO compiles, and the split is required.**
 * The `-I' is what makes `ctype.c' see APExp's <ctype.h>, so
 * `_ctype[]' is built with APExp's `_IS*' values -- against glibc's
 * header it would get glibc's bits and the table would be measured
 * with the wrong constants. But that same `-I' must NOT reach this
 * file: it would pull APExp's <stdio.h>, which includes
 * <stdarg_arch.h> from the per-architecture directory and does not
 * exist on the host. One command cannot want both header sets.
 *
 * ------------------------------------------------------------------
 * THE BUG IT CAME FROM: ONE MISSING FLAG ON ONE ENTRY.
 *
 * `_ctype[9]' -- TAB -- was `_ISspace|_IScntrl' with **no
 * _ISblank**, so `isblank('\t')' answered FALSE. C99 7.4.1.3 says
 * isblank is true for exactly space and horizontal tab in the "C"
 * locale.
 *
 * It surfaced as bash being unable to run any script with a
 * TAB-INDENTED line, dying `Killed: Insufficient physical memory'
 * after ~17 million allocations -- and it took an enormous hunt,
 * because nothing in the symptom points at ctype:
 *
 *   bash's syntax.c is GENERATED by its own mksyntax, whose
 *   addblanks() does `if (isblank (uc)) lsyntax[uc] |= CBLANK;'. So
 *   TAB got `CSHBRK' with no `CBLANK'. bash's `shellblank()' reads
 *   CBLANK and `shellbreak()' reads CSHBRK -- so a tab was NOT
 *   whitespace to skip, but WAS a word delimiter. read_token handed
 *   the tab to read_token_word, which ungot it and returned a
 *   ZERO-LENGTH word; the parser appended that empty word and asked
 *   for another token. For ever, one WORD_LIST per turn.
 *
 * *The wrong answer was frozen into a generated file at build time*,
 * so fixing the library alone would not have fixed bash -- syntax.c
 * had to be corrected too.
 *
 * ------------------------------------------------------------------
 * WHY IT SWEEPS ALL 256 RATHER THAN CHECKING TAB.
 *
 * A test that asked only `isblank('\t')' would pass the moment the
 * flag went in and would say nothing about the other 255 entries or
 * the other eleven classifications -- and the table is hand-written,
 * so one wrong entry is exactly as likely as another. This asks every
 * cell: 256 values by 12 functions, 3072 comparisons, and it prints
 * every disagreement with the character, the class, and both answers.
 *
 * ON >= 128: in the C locale every classification is false for every
 * byte above 127, and glibc agrees, so those are checked rather than
 * skipped. *A range excluded from a sweep is a range not tested*, and
 * this table has entries up there.
 *
 * ------------------------------------------------------------------
 * THE HEADER COLLISION, AND HOW THIS AVOIDS IT.
 *
 * glibc's <ctype.h> and APExp's both define `_ISupper', `_ISblank'
 * and friends, with DIFFERENT VALUES, and both define the is*()
 * names as macros. Including them together does not work.
 *
 * So this file includes NEITHER. It declares the twelve glibc
 * functions itself and captures them in function pointers FIRST, then
 * declares APExp's bits and table by hand. The captured pointers are
 * real glibc, so the reference is the reference; and the APExp side is
 * read straight out of the linked `_ctype[]'.
 *
 * **The bit values below are copied from sys/include/ape/ctype.h and
 * must match it.** That is the one thing this file cannot check for
 * itself, so section 0 prints the derived classification of 'A', '0',
 * ' ' and '\t' -- if the constants were wrong, those four lines would
 * be visibly nonsense before any comparison is read.
 */

#include <stdio.h>

/* glibc's, declared rather than included -- see the header note. */
extern int isalnum(int);
extern int isalpha(int);
extern int isblank(int);
extern int iscntrl(int);
extern int isdigit(int);
extern int isgraph(int);
extern int islower(int);
extern int isprint(int);
extern int ispunct(int);
extern int isspace(int);
extern int isupper(int);
extern int isxdigit(int);

static int (*const ref[12])(int) = {
	isalnum, isalpha, isblank, iscntrl, isdigit, isgraph,
	islower, isprint, ispunct, isspace, isupper, isxdigit,
};
static const char *const name[12] = {
	"isalnum", "isalpha", "isblank", "iscntrl", "isdigit", "isgraph",
	"islower", "isprint", "ispunct", "isspace", "isupper", "isxdigit",
};

/* APExp's, copied from sys/include/ape/ctype.h. Section 0 is the
 * check that they were copied right. */
enum {
	A_ISupper  = 01,
	A_ISlower  = 02,
	A_ISdigit  = 04,
	A_ISspace  = 010,
	A_ISpunct  = 020,
	A_IScntrl  = 040,
	A_ISblank  = 0100,
	A_ISxdigit = 0200,
};

extern unsigned char _ctype[];	/* from ap/ctype/ctype.c */

#define M(c)	(_ctype[(unsigned char)(c)])

/* The twelve, spelled exactly as APExp's header and isprint.c spell
 * them. isprint is the one that is NOT a single mask -- see
 * ap/ctype/isprint.c for why. */
static int a_isalnum(int c)  { return !!(M(c)&(A_ISupper|A_ISlower|A_ISdigit)); }
static int a_isalpha(int c)  { return !!(M(c)&(A_ISupper|A_ISlower)); }
static int a_isblank(int c)  { return !!(M(c)&A_ISblank); }
static int a_iscntrl(int c)  { return !!(M(c)&A_IScntrl); }
static int a_isdigit(int c)  { return !!(M(c)&A_ISdigit); }
static int a_isgraph(int c)  { return !!(M(c)&(A_ISpunct|A_ISupper|A_ISlower|A_ISdigit)); }
static int a_islower(int c)  { return !!(M(c)&A_ISlower); }
static int a_isprint(int c)  { return c == ' ' ? 1 :
	!!(M(c)&(A_ISpunct|A_ISupper|A_ISlower|A_ISdigit)); }
static int a_ispunct(int c)  { return !!(M(c)&A_ISpunct); }
static int a_isspace(int c)  { return !!(M(c)&A_ISspace); }
static int a_isupper(int c)  { return !!(M(c)&A_ISupper); }
static int a_isxdigit(int c) { return !!(M(c)&A_ISxdigit); }

static int (*const ape[12])(int) = {
	a_isalnum, a_isalpha, a_isblank, a_iscntrl, a_isdigit, a_isgraph,
	a_islower, a_isprint, a_ispunct, a_isspace, a_isupper, a_isxdigit,
};

static void
show(const char *what, int c)
{
	int i;

	printf("  %-6s %3d  0x%02x  ", what, c, M(c));
	for(i = 0; i < 12; i++)
		if(ape[i](c))
			printf("%s ", name[i]);
	printf("\n");
}

static const char *
charname(int c)
{
	static char b[8];

	if(c == ' ')  return "SPC";
	if(c == '\t') return "TAB";
	if(c == '\n') return "LF";
	if(c < 32 || c > 126){ sprintf(b, "\\%03o", c); return b; }
	sprintf(b, "'%c'", c);
	return b;
}

int
main(void)
{
	int c, i, wrong, total;

	printf("ctype-xcheck: libap's _ctype[] against glibc, 256 x 12\n\n");

	/*
	 * 0. THE CONSTANTS. If A_IS* were miscopied from the header,
	 *    every comparison below would be measuring the wrong bits
	 *    while still looking like a real test. These four lines are
	 *    readable by eye: 'A' upper+alpha+alnum+graph+print+xdigit,
	 *    '0' digit+alnum+graph+print+xdigit, SPC space+blank+print,
	 *    TAB space+cntrl+blank and NOT print.
	 */
	printf("0. the bit constants, read off the linked table:\n");
	show("'A'", 'A');
	show("'0'", '0');
	show("SPC", ' ');
	show("TAB", '\t');
	printf("\n");

	/*
	 * 1. THE SWEEP. Every value, every classification, both sides.
	 */
	wrong = total = 0;
	for(c = 0; c < 256; c++)
		for(i = 0; i < 12; i++){
			int r = !!ref[i](c);
			int a = ape[i](c);

			total++;
			if(r != a){
				if(wrong == 0)
					printf("1. DISAGREEMENTS (char, class, glibc, libap):\n");
				printf("  %-5s %3d  %-8s glibc=%d libap=%d\n",
					charname(c), c, name[i], r, a);
				wrong++;
			}
		}

	printf("\n%d of %d comparisons wrong\n", wrong, total);
	if(wrong == 0)
		printf("PASS -- the table agrees with glibc everywhere\n");
	else
		printf("FAIL\n");
	return wrong != 0;
}
