APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

DWSRC=$APEXPROOT/sys/src/external/libdwarf

BIN=$APEXPROOT/$objtype/bin/ape

TARG=dw2elf

OFILES=\
	dw2elf.$O\

<$APEXPROOT/sys/src/cmd/mkone

CC=pcc
LD=pcc
CFLAGS=-c\
	-I$DWSRC/src/lib/libdwarf\
