APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

DWSRC=$APEXPROOT/sys/src/external/libdwarf

LIB=\
	$APEXPROOT/$objtype/lib/ape/libdwarfp.a\
	$APEXPROOT/$objtype/lib/ape/libdwarf.a\
	$APEXPROOT/$objtype/lib/ape/libzstd.a\

BIN=$APEXPROOT/$objtype/bin/ape

TARG=dw2elf

OFILES=\
	dw2elf.$O\

<$APEXPROOT/sys/src/cmd/mkone

CC=pcc
LD=pcc
CFLAGS=-c\
	-I$DWSRC/src/lib/libdwarf\
	-I$DWSRC/src/lib/libdwarfp\
