APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
# musl \
	fegetexceptflag.$O\
	feholdexcept.$O\
	fesetexceptflag.$O\
	fesetround.$O\
	feupdateenv.$O\
	fenv.$O

<$APEXPROOT/sys/src/cmd/mksyslib

CC=pcc
CFLAGS=$CFLAGS -c -D_POSIX_SOURCE -D_BSD_SOURCE\
		-I$APEXPROOT/sys/include/ape -I$APEXPROOT/$objtype/include/ape
		-
# TODO: figure out how to build the arch-specific fenv objects
# We have a dependency issue: as needs APExp libraries so it is built after

fenv.$O: dummy/fenv.c
	$CC $CFLAGS -o $target $prereq


