</$objtype/mkfile
APEXPROOT=../../../../..
TARG=bash

OFILES=\
	shell.$O\
	eval.$O\
	parse.$O\
	general.$O\
	make_cmd.$O\
	print_cmd.$O\
	dispose_cmd.$O\
	execute_cmd.$O\
	variables.$O\
	copy_cmd.$O\
	error.$O\
	expr.$O\
	flags.$O\
#	jobs.$O\
	nojobs.$O\
	subst.$O\
	hashcmd.$O\
	hashlib.$O\
	mailcheck.$O\
	trap.$O\
	input.$O\
	unwind_prot.$O\
	pathexp.$O\
	sig.$O\
	test.$O\
	version.$O\
	alias.$O\
	array.$O\
	arrayfunc.$O\
	assoc.$O\
	braces.$O\
	bracecomp.$O\
	bashhist.$O\
	bashline.$O\
	sig.$O\
	siglist.$O\
	list.$O\
	stringlib.$O\
	locale.$O\
	findcmd.$O\
	redir.$O\
	pcomplete.$O\
	pcomplib.$O\
	syntax.$O\
	xmalloc.$O\
# termcap - force linking... \
#	termcap.$O\
#	tparam.$O\
# tilde -force linking \
	tilde.$O\


BASHSRC=../../../external/bash

BASHLIBS=\
	libbuiltins.a$O\
	libglob.a$O\
	libsh.a$O

LIB= $BASHLIBS

BIN=$APEXPROOT/$objtype/bin/ape

<$APEXPROOT/sys/src/cmd/mkone

CC=pcc
LD=pcc

DEFS= 	-DHAVE_CONFIG_H -DLOCALEDIR="/sys/lib/ape/locale" -D_POSIX_SOURCE\
		-D_BSD_EXTENSION -DHAVE_LIMITS_H -D_LIMITS_EXTENSION -DPLAN9\
		-DCONF_OSTYPE="Plan9" -DCONF_MACHTYPE="$objtype-unknown-Plan9" -DPROGRAM="Bash"\
		-DPACKAGE="Bash" -DPACKAGE_STRING='bash 5.2-release'\
		-DCONF_VENDOR="unknonw" -DCONF_HOSTTYPE="$objtype"\
		-DHAVE_SYS_RESOURCE_H -DTERM=xterm

CFLAGS=	-c -B -I. -I$BASHSRC -I$BASHSRC/include -I$BASHSRC/lib $DEFS

%.$O: $BASHSRC/%.c
	$CC $CFLAGS $BASHSRC/$stem.c

termcap.$O: $BASHSRC/lib/termcap/termcap.c
	$CC $CFLAGS $BASHSRC/lib/termcap/termcap.c

tparam.$O: $BASHSRC/lib/termcap/tparam.c
	$CC $CFLAGS $BASHSRC/lib/termcap/tparam.c

tilde.$O: $BASHSRC/lib/tilde/tilde.c
	$CC $CFLAGS $BASHSRC/lib/tilde/tilde.c

libsh.a$O: $BASHSRC/lib/sh/Makefile
			make -C $BASHSRC/lib/sh
			mv $BASHSRC/lib/sh/libsh.a libsh.a$O
			ar d libsh.a$O strtoimax.o # conflict with libap
			rm $BASHSRC/lib/sh/*.o

libglob.a$O: $BASHSRC/lib/glob/Makefile
			make -C $BASHSRC/lib/glob
			mv $BASHSRC/lib/glob/libglob.a libglob.a$O
			rm $BASHSRC/lib/glob/*.o

libmalloc.a$O: $BASHSRC/lib/malloc/Makefile
			make -C $BASHSRC/lib/malloc
			mv $BASHSRC/lib/malloc/libmalloc.a libmalloc.a$O
			rm $BASHSRC/lib/malloc/*.o

libreadline.a$O: $BASHSRC/lib/readline/Makefile
			make -C $BASHSRC/lib/readline libhistory.a
			mv $BASHSRC/lib/readline/libreadline.a libreadline.a$O
			mv $BASHSRC/lib/readline/libhistory.a libhistory.a$O
			rm $BASHSRC/lib/readline/*.o

libintl.a$O: $BASHSRC/lib/intl/Makefile
			make -C $BASHSRC/lib/intl
			mv $BASHSRC/lib/intl/libintl.a libintl.a$O
			rm $BASHSRC/lib/intl/*.o

libbuiltins.a$O: $BASHSRC/builtins/Makefile
			make -C $BASHSRC/builtins
			mv $BASHSRC/builtins/libbuiltins.a libbuiltins.a$O
			rm $BASHSRC/builtins/*.o
			rm $BASHSRC/builtins/mkbuiltins
			rm $BASHSRC/builtins/psize.aux

install:V:
		cp $BIN/bash $BIN/sh
		cp $GSEDSRC/doc/bash.1 $APEXPROOT/sys/man/1/bash

clean:V:
	rm -f *.[$OS] [$OS].out lib*.a*



