</$objtype/mkfile
APEXPROOT=../../../../..
TARG=bash

OFILES=\
	shell.$O\
	eval.$O\
	parse.$O\
	general.$O\
	make_cmd.$O\
	print_cmd.$O\
	dispose_cmd.$O\
	execute_cmd.$O\
	variables.$O\
	copy_cmd.$O\
	error.$O\
	expr.$O\
	flags.$O\
	nojobs.$O\
	subst.$O\
	hashcmd.$O\
	hashlib.$O\
	mailcheck.$O\
	trap.$O\
	input.$O\
	unwind_prot.$O\
	pathexp.$O\
	sig.$O\
	test.$O\
	version.$O\
	alias.$O\
	array.$O\
	arrayfunc.$O\
	assoc.$O\
	braces.$O\
	bracecomp.$O\
	bashhist.$O\
	bashline.$O\
	list.$O\
	stringlib.$O\
	locale.$O\
	findcmd.$O\
	redir.$O\
	pcomplete.$O\
	pcomplib.$O\
	syntax.$O\
	xmalloc.$O

OBJTERMCAP= tc-termcap.$O tc-tparam.$O

OBJTILDE= ti-tilde.$O

OBJGLOB= glob.$O strmatch.$O smatch.$O xmbsrtowcs.$O gmisc.$O

OBJBUILTINS=bi-builtins.$O \
	bi-alias.$O bi-bind.$O bi-break.$O bi-builtin.$O bi-caller.$O bi-cd.$O bi-colon.$O bi-command.$O \
	bi-common.$O bi-declare.$O bi-echo.$O bi-enable.$O bi-eval.$O bi-evalfile.$O \
	bi-evalstring.$O bi-exec.$O bi-exit.$O bi-fc.$O bi-fg_bg.$O bi-hash.$O bi-help.$O bi-history.$O \
	bi-jobs.$O bi-kill.$O bi-let.$O bi-mapfile.$O \
	bi-pushd.$O bi-read.$O bi-return.$O bi-set.$O bi-setattr.$O bi-shift.$O bi-source.$O \
	bi-suspend.$O bi-test.$O bi-times.$O bi-trap.$O bi-type.$O bi-ulimit.$O bi-umask.$O \
	bi-wait.$O bi-getopts.$O bi-shopt.$O bi-printf.$O bi-getopt.$O bi-bashgetopt.$O bi-complete.$O

OBJSH= clktck.$O clock.$O getenv.$O oslib.$O setlinebuf.$O strnlen.$O \
	itos.$O zread.$O zwrite.$O shtty.$O shmatch.$O eaccess.$O \
	netconn.$O netopen.$O timeval.$O makepath.$O pathcanon.$O \
	pathphys.$O tmpfile.$O stringlist.$O stringvec.$O spell.$O shquote.$O \
	strtrans.$O snprintf.$O mailstat.$O fmtulong.$O \
	fmtullong.$O fmtumax.$O zcatfd.$O zmapfd.$O winsize.$O wcsdup.$O \
	fpurge.$O zgetline.$O mbscmp.$O mbsncmp.$O uconvert.$O ufuncs.$O casemod.$O \
	input_avail.$O mbscasecmp.$O fnxform.$O unicode.$O shmbchar.$O strvis.$O \
	strscpy.$O anonfile.$O compat.$O \
	utf8.$O random.$O gettimeofday.$O timers.$O wcsnwidth.$O\
	mktime.$O mbschr.$O getcwd.$O

BASHSRC=$APEXPROOT/sys/src/external/bash

BASHLIBS=\
	libtermcap.a$O\
	libtilde.a$O\
	libbuiltins.a$O\
	libglob.a$O\
	libsh.a$O\

#link libap first to already occupy symbols supported by the system libap
LIB= $APEXPROOT/$objtype/lib/ape/libap.a $BASHLIBS $APEXPROOT/$objtype/lib/ape/libreadline.a

BIN=$APEXPROOT/$objtype/bin/ape

<$APEXPROOT/sys/src/cmd/mkone

CC=pcc
LD=pcc
YACC=bison

DEFS= 	-DHAVE_CONFIG_H -DLOCALEDIR="/sys/lib/ape/locale" -D_POSIX_SOURCE\
		-D_BSD_EXTENSION -DHAVE_LIMITS_H -D_LIMITS_EXTENSION -DPLAN9\
		-DCONF_OSTYPE="plan9" -DCONF_MACHTYPE="$objtype-apexp-plan9" -DPROGRAM="bash"\
		-DPACKAGE="bash" -DPACKAGE_STRING='bash 5.3-release'\
		-DCONF_VENDOR="apexp" -DCONF_HOSTTYPE="$objtype"\
		-DHAVE_SYS_RESOURCE_H -DTERM=vt100 -UJOB_CONTROL\
		-Dbotch=programming_error -DSHELL


CFLAGS=	-c -B -I. -I$BASHSRC -I$BASHSRC/include -I$BASHSRC/lib -I$BASHSRC/lib/intl\
		$DEFS

BASHSRC=$APEXPROOT/sys/src/external/bash

# Native rules for building mkbuiltins and generating source files
# Note: These need to be built using the host compiler (the host-native cc)
# because they generate code that is compiled into the bash binary.

MKBUILTINS=$BASHSRC/builtins/mkbuiltins

DEFFILES=alias.def bind.def break.def builtin.def caller.def cd.def colon.def command.def declare.def echo.def enable.def eval.def getopts.def exec.def exit.def fc.def fg_bg.def hash.def help.def history.def jobs.def kill.def let.def read.def return.def set.def setattr.def shift.def source.def suspend.def test.def times.def trap.def type.def ulimit.def umask.def wait.def reserved.def pushd.def shopt.def printf.def complete.def mapfile.def

$MKBUILTINS: $BASHSRC/builtins/mkbuiltins.c
	cc -I$BASHSRC -I$BASHSRC/include -o $MKBUILTINS $prereq

# Generate builtins.c and builtext.h
$BASHSRC/builtins/builtins.c $BASHSRC/builtins/builtext.h: $MKBUILTINS
	@echo "Generating builtins.c and builtext.h..."
	@(cd $BASHSRC/builtins && ./mkbuiltins -externfile builtext.h -structfile builtins.c -noproduction -D . $DEFFILES)
	for (i in $DEFFILES)
		@(cd $BASHSRC/builtins && ./mkbuiltins -D . $stem.def)

$OBJBUILTINS: $BASHSRC/builtins/builtins.c

%.$O: %.c
			$CC $CFLAGS $stem.c

%.$O: $BASHSRC/%.c
			$CC $CFLAGS $BASHSRC/$stem.c

bi-%.$O: $BASHSRC/builtins/%.c
			$CC $CFLAGS -I$BASHSRC/builtins $BASHSRC/builtins/$stem.c -o $target

tc-%.$O: $BASHSRC/lib/termcap/%.c
			$CC $CFLAGS -I$BASHSRC/lib/termcap $BASHSRC/lib/termcap/$stem.c

ti-%.$O: $BASHSRC/lib/tilde/%.c
			$CC $CFLAGS -I$BASHSRC/lib/tilde $BASHSRC/lib/tilde/$stem.c -o $target

%.$O: $BASHSRC/lib/sh/%.c
			$CC $CFLAGS -I$BASHSRC/lib/sh $BASHSRC/lib/sh/$stem.c

%.$O: $BASHSRC/lib/glob/%.c
			$CC $CFLAGS -I$BASHSRC/lib/glob $BASHSRC/lib/glob/$stem.c


libtermcap.a$O: $OBJTERMCAP
			ar vu $target $prereq

libtilde.a$O: $OBJTILDE
			ar vu $target $prereq

libsh.a$O: $OBJSH
			ar vu $target $prereq

libglob.a$O: $OBJGLOB
			ar vu $target $prereq

libbuiltins.a$O: $OBJBUILTINS
			ar vu $target $prereq

install:V:
			cp $BASHSRC/doc/bash.1 $APEXPROOT/sys/man/1/bash

clean:V:
			rm -f *.[$OS] [$OS].$Out lib*.a* $MKBUILTINS





