</$objtype/mkfile
APEXPROOT=../../../../../
LIB=$APEXPROOT/$objtype/lib/ape/libcurses.a

OFILES=\
# pdcurses \
	addch.$O\
	addchstr.$O\
	addstr.$O\
	attr.$O\
	beep.$O\
	bkgd.$O\
	border.$O\
	clear.$O\
	color.$O\
	debug.$O\
	delch.$O\
	deleteln.$O\
	getch.$O\
	getstr.$O\
	getyx.$O\
	inch.$O\
	inchstr.$O\
	initscr.$O\
	inopts.$O\
	insch.$O\
	insstr.$O\
	instr.$O\
	kernel.$O\
	keyname.$O\
	mouse.$O\
	move.$O\
	outopts.$O\
	overlay.$O\
	pad.$O\
	panel.$O\
	printw.$O\
	refresh.$O\
	scanw.$O\
	scr_dump.$O\
	scroll.$O\
	slk.$O\
	termattr.$O\
	terminfo.$O\
	touch.$O\
	util.$O\
	window.$O\
# plan9 \
	pdcclip.$O\
	pdcdisp.$O\
	pdcgetsc.$O\
	pdckbd.$O\
	pdcscrn.$O\
	pdcsetsc.$O\
	pdcutil.$O\
# common\
	common-pdccolor.$O\
	common-psf.$O

HFILES=\
	$APEXPROOT/sys/include/ape/curses.h\
	$APEXPROOT/sys/include/ape/panel.h\
	$APEXPROOT/sys/include/ape/term.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/$objtype/%}\

<$APEXPROOT/sys/src/cmd/mksyslib

CURSRC=../../../external/PDCursesMod

CC=pcc
LD=pcc
# __bool_true_false_are_defined says "bool, true and false already
# exist, do not define them", and it is normally <stdbool.h> that says
# so. curses.h:136 is
#
#	#if !defined(PDC_PP98) && !defined(__bool_true_false_are_defined)
#	typedef unsigned char bool;
#	#endif
#
# and nothing on the way to it includes <stdbool.h>, so PDCurses reached
# for its own bool. kencc reserves bool as a keyword whether or not the
# header was included, so that typedef cannot be accepted:
#
#	curses.h:136 syntax error, last name: bool
#
# It used to parse by accident. While bool was LCHAR, the line was
# LTYPEDEF LUNSIGNED LCHAR LCHAR ';', which gctnlist absorbed as a
# declaration with no declarator -- a silent no-op that left bool
# meaning signed char. Now that bool is its own token it cannot follow
# "unsigned char", and the accident is a diagnostic.
#
# Defining it here rather than adding an include to upstream's header:
# it is the same answer <stdbool.h> would give, and the value matches
# that header's token for token, which cpp requires of a macro defined
# twice -- white space included. See the macro identity note in
# CLAUDE.md.
CFLAGS= -c -I$CURSRC -I$CURSRC/plan9 -I$CURSRC/common -D_POSIX_SOURCE \
-D_BSD_EXTENSION -D_C99_SNPRINTF_EXTENSION -DHAVE_VSNPRINTF -DHAVE_GETTIMEOFDAY -DPDC_FORCE_UTF8 \
-D__bool_true_false_are_defined=1

%.$O: $CURSRC/pdcurses/%.c
	$CC $CFLAGS $CURSRC/pdcurses/$stem.c

%.$O: $CURSRC/plan9/%.c
	$CC $CFLAGS $CURSRC/plan9/$stem.c

common-%.$O: $CURSRC/common/%.c
	$CC $CFLAGS -c $prereq -o $target

install:V:
	cp $CURSRC/docs/MANUAL.md $APEXPROOT/sys/man/1/pdcurses

demos:V:
	@{
		mk -f mkfile_demo all
	}

clean:V:
	@{
		mk -f mkfile_demo clean
	}
	rm -f *.[$OS]

nuke:V:
	rm -f $LIB
