APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

MUSRC=$APEXPROOT/sys/src/external/muon

BIN=$APEXPROOT/$objtype/bin/ape
TARG=muon init

OFILES=\
# .\
	version.$O\
# src/backend\
	backend.$O\
	common_args.$O\
	introspect.$O\
	output.$O\
	xcode.$O\
	ninja.$O\
# src/backend/ninja\
	ninja-alias_target.$O\
	ninja-build_target.$O\
	ninja-coverage.$O\
	ninja-custom_target.$O\
	ninja-rules.$O\
# src/datastructures\
	arr.$O\
	bucket_arr.$O\
	hash.$O\
	stack.$O\
# src/formats\
	editorconfig.$O\
	ini.$O\
	json.$O\
	lines.$O\
	tap.$O\
	xml.$O\
# src/functions\
	array.$O\
	boolean.$O\
	both_libs.$O\
	build_target.$O\
	compiler.$O\
	configuration_data.$O\
	custom_target.$O\
	dependency.$O\
	dict.$O\
	disabler.$O\
	environment.$O\
	external_program.$O\
	feature_opt.$O\
	file.$O\
	generator.$O\
	machine.$O\
	meson.$O\
	modules.$O\
	number.$O\
	run_result.$O\
	source_configuration.$O\
	source_set.$O\
	string.$O\
	subproject.$O\
	kernel.$O\
# src/functions/kernel\
	k-build_target.$O\
	k-configure_file.$O\
	k-custom_target.$O\
	k-dependency.$O\
	k-install.$O\
	k-options.$O\
	k-subproject.$O\
# src/functions/modules\
	mod-curl.$O\
	mod-fs.$O\
	mod-getopt.$O\
	mod-json.$O\
	mod-keyval.$O\
	mod-pkgconfig.$O\
	mod-python.$O\
	mod-sourceset.$O\
	mod-subprojects.$O\
	mod-toolchain.$O\
# src/lang\
	l-analyze.$O\
	l-compiler.$O\
	l-eval.$O\
	l-fmt.$O\
	l-func_lookup.$O\
	l-lexer.$O\
	l-lsp.$O\
	l-object.$O\
	l-object_iterators.$O\
	l-parser.$O\
	l-serial.$O\
	l-string.$O\
	l-typecheck.$O\
	l-vm.$O\
	l-workspace.$O\
# src\
	args.$O\
	cmd_install.$O\
	cmd_subprojects.$O\
	cmd_test.$O\
	coerce.$O\
	compilers.$O\
	embedded.$O\
	error.$O\
	guess.$O\
	install.$O\
	log.$O\
	machine_file.$O\
	machines.$O\
	main.$O\
	memmem.$O\
	meson_opts.$O\
	options.$O\
	opts.$O\
	rpmvercmp.$O\
	sha_256.$O\
	vsenv.$O\
	wrap.$O\
	ui_null.$O\
# src/platform\
	filesystem.$O\
	log.$O\
	os.$O\
	path.$O\
	run_cmd.$O\
	uname.$O\
# src/platform/posix\
	p-init.$O\
	p-rpath_fixer.$O\
	p-term.$O\
	p-timer.$O\
# src/external\
	libcurl.$O\
	samurai.$O\
	readline_bestline.$O\
	pkgconfig.$O

LIB=

<$APEXPROOT/sys/src/cmd/mkone


CFLAGS=-c -I$MUSRC/include -DMUON_STATIC -DMUON_PLATFORM_posix

%.$O: %.c
	$CC $CFLAGS $stem.c

%.$O: $MUSRC/tools/%.c
	$CC $CFLAGS $MUSRC/tools/$stem.c

%.$O: $MUSRC/src/%.c
	$CC $CFLAGS $MUSRC/src/$stem.c

%.$O: $MUSRC/src/backend/%.c
	$CC $CFLAGS $MUSRC/src/backend/$stem.c

ninja-%.$O: $MUSRC/src/backend/ninja/%.c
	$CC $CFLAGS $MUSRC/src/backend/ninja/$stem.c -o $target

%.$O: $MUSRC/src/datastructures/%.c
	$CC $CFLAGS $MUSRC/src/datastructures/$stem.c

%.$O: $MUSRC/src/formats/%.c
	$CC $CFLAGS $MUSRC/src/formats/$stem.c

%.$O: $MUSRC/src/functions/%.c
	$CC $CFLAGS $MUSRC/src/functions/$stem.c

k-%.$O: $MUSRC/src/functions/kernel/%.c
	$CC $CFLAGS $MUSRC/src/functions/kernel/$stem.c -o $target

mod-%.$O: $MUSRC/src/functions/modules/%.c
	$CC $CFLAGS $MUSRC/src/functions/modules/$stem.c -o $target

l-%.$O: $MUSRC/src/lang/%.c
	$CC $CFLAGS $MUSRC/src/lang/$stem.c -o $target

%.$O: $MUSRC/src/platform/%.c
	$CC $CFLAGS $MUSRC/src/platform/$stem.c

p-%.$O: $MUSRC/src/platform/posix/%.c
	$CC $CFLAGS $MUSRC/src/platform/posix/$stem.c -o $target

%.$O: $MUSRC/src/external/%.c
	$CC $CFLAGS $MUSRC/src/external/$stem.c






