</$objtype/mkfile
APEXPROOT=../../../../..
TARG=pcre2grep
OFILES=pcre2grep.$O 
LIB=$APEXPROOT/$objtype/lib/ape/libpcre2.a $APEXPROOT/$objtype/lib/ape/libpcre2posix.a
BIN=$APEXPROOT/$objtype/bin/ape
HFILES=$APEXPROOT/sys/include/ape/pcre2.h config.h

<$APEXPROOT/sys/src/cmd/mkone

PCRESRC=../../../external/pcre2

CC=pcc
LD=pcc
CFLAGS=-c -I. -I$PCRESRC/src -DHAVE_CONFIG_H 

pcre2grep.$O: $PCRESRC/src/pcre2grep.c
	$CC $CFLAGS $PCRESRC/src/pcre2grep.c

install:V:
	cp $O.out $BIN/pcre2grep
	cp $O.out $BIN/grep
	cp egrep $APEXPROOT/rc/bin/ape/
	cp fgrep $APEXPROOT/rc/bin/ape/



