</$objtype/mkfile
TARG=pcregrep
OFILES=pcregrep.$O 
LIB=/$objtype/lib/ape/libpcre.a /$objtype/lib/ape/libpcreposix.a
BIN=/$objtype/bin/ape
HFILES=/sys/include/ape/pcre.h config.h

</sys/src/cmd/mkone

PCRESRC=../../../external/pcre

CC=pcc
LD=pcc
CFLAGS=-c -I. -I$PCRESRC -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_RESEARCH_SOURCE -D_REENTRANT_SOURCE \
	-D_BSD_EXTENSION -D_NET_EXTENSION -D_LIMITS_EXTENSION -D_C99_SNPRINTF_EXTENSION \
	-D_REGEXP_EXTENSION -DHAVE_SOCK_OPTS -DHAVE_CONFIG_H 

pcregrep.$O: $PCRESRC/pcregrep.c
	$CC $CFLAGS $PCRESRC/pcregrep.c



