</$objtype/mkfile
TARG=pcre2grep
OFILES=pcre2grep.$O 
LIB=/$objtype/lib/ape/libpcre2.a /$objtype/lib/ape/libpcre2posix.a
BIN=/$objtype/bin/ape
HFILES=/sys/include/ape/pcre2.h config.h

</sys/src/cmd/mkone

PCRESRC=../../../external/pcre2

CC=pcc
LD=pcc
CFLAGS=-c -I. -I$PCRESRC/src -DHAVE_CONFIG_H 

pcre2grep.$O: $PCRESRC/src/pcre2grep.c
	$CC $CFLAGS $PCRESRC/src/pcre2grep.c

install:V:
	cp $O.out $BIN/pcre2grep
	cp $O.out $BIN/grep
	cp egrep /rc/bin/ape/
	cp fgrep /rc/bin/ape/



