</$objtype/mkfile
APEXPROOT=../../../../..

TARG=iconv

OFILES= iconv.$O

BIN=$APEXPROOT/$objtype/bin/ape

<$APEXPROOT/sys/src/cmd/mkone

#during building from scratch, the new pcc is not picked up and compilation
#fails on include_next
CC=$APEXPROOT/$objtype/bin/pcc

CFLAGS=-c -D_POSIX_SOURCE -D_BSD_EXTENSION\
		-DLOCALEDIR="/sys/lib/ape/locale"\


install:V:
	



