BUILTINS=
</$objtype/mkfile
<../c++mkfile

%.$O:	%.c
	$CC $stem.c

$O.out:	munch.$O
	$LD $prereq 

install:V: $O.out
	mv $O.out /$objtype/bin/c++/munch

clean:V:
	rm -f *.[$OS] [$OS].out y.tab.?

nuke:V: clean
