APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libgettextpo.a

SRCDIR=\
# src \
	str-list.$O\
	message.$O\
	pos.$O\
	msgl-ascii.$O\
	write-catalog.$O\
	write-po.$O\
	po-charset.$O\
	read-catalog-special.$O\
	read-catalog-abstract.$O\
	read-catalog.$O\ read-po.$O\
	read-po-lex.$O\
	read-po-gram.$O\
	plural-table.$O\
	format-c.$O\
	format-c++-brace.$O\
	format-python.$O\
	format-python-brace.$O\
	format-java.$O\
	format-java-printf.$O\
	format-csharp.$O\
	format-javascript.$O\
	format-scheme.$O\
	format-lisp.$O\
	format-elisp.$O\
	format-librep.$O\
	format-rust.$O\
	format-go.$O\
	format-ruby.$O\
	format-sh.$O\
	format-sh-printf.$O\
	format-awk.$O\
	format-lua.$O\
	format-pascal.$O\
	format-modula2.$O\
	format-d.$O\
	format-ocaml.$O\
	format-smalltalk.$O\
	format-qt.$O\
	format-qt-plural.$O\
	format-kde.$O\
	format-kde-kuit.$O\
	format-boost.$O\
	format-tcl.$O\
	format-perl.$O\
	format-perl-brace.$O\
	format-php.$O\
	format-gcc-internal.$O\
	format-gfc-internal.$O\
	format.$O\
	plural-exp.$O\
	plural-eval.$O\
	msgl-check.$O\
	sentence.$O\

OFILES= \
# libgettextpo \
	gettext-po.$O\
	$SRCDIR\

<$APEXPROOT/sys/src/cmd/mksyslib

GETTEXTSRC=../../../external/gettext/gettext-tools/libgettextpo

#during building from scratch, the new pcc is not picked up and compilation
#fails on include_next
CC=$APEXPROOT/$objtype/bin/pcc

UNRPL=	-Drpl_strtol=strtol -Drpl_realloc=realloc -Drpl_strtoul=strtoul -Drpl_strstr=strstr\
		-Drpl_strerror=strerror -Drpl_calloc=calloc -Drpl_readlink=readlink\
		-Drpl_getcwd=getcwd -Drpl_open=open -Drpl_dup2=dup2 -Drpl_malloc=malloc -Drpl_free=free\
		-Drpl_unlink=unlink -Drpl_lstat=lstat

DEFS=	-DHAVE_SETEUID -DHAVE_SETEGID -Dseteuid=setuid -Dsetegid=setgid\
		-DHAVE_CONFIG_H -D_POSIX_SOURCE -D_BSD_EXTENSION -D_RESEARCH_SOURCE\
		-DLIBDIR="/sys/lib/ape" -DHAVE_ICONV -DHAVE_STPCPY\
		-DUINTPTR_MAX=INT_MAX -DUINTPTR_WIDTH=UINTPTR_MAX -DUCHAR_WIDTH=UCHAR_MAX


CFLAGS=-c -B -I. -I$GETTEXTSRC -I$GETTEXTSRC/.. -I$GETTEXTSRC/../src\
		-I$GETTEXTSRC/../../libtextstyle/lib\
		$UNRPL $DEFS


%.$O: $GETTEXTSRC/%.c
	$CC $CFLAGS $GETTEXTSRC/$stem.c

%.$O: $GETTEXTSRC/../src/%.c
	$CC $CFLAGS $GETTEXTSRC/../src/$stem.c











