</$objtype/mkfile
APEXPROOT=../../../..
BIN=$APEXPROOT/$objtype/bin

TARG=vts
OFILES=\
	main.$O\
	srv.$O\
	session.$O\
	cells.$O\
	celldiff.$O\
	engine.$O\
	lined.$O\

HFILES=dat.h\
	fns.h\
	cells.h\
	celldiff.h\
	compat.h\
	engine.h\
	session.h\
	lined.h\

<$APEXPROOT/sys/src/cmd/mkone

CFLAGS= -I$APEXPROOT/sys/include

$O.out:	$APEXPROOT/$objtype/lib/libvterm.a /$objtype/lib/lib9p.a /$objtype/lib/libthread.a /$objtype/lib/libc.a



