</$objtype/mkfile
APEXPROOT=../../../..
TARG=1c
OFILES=\
	cgen.$O\
	reg.$O\
	txt.$O\
	peep.$O\
	swt.$O\
	sgen.$O\
	list.$O\
	enam.$O\
	mul.$O\

HFILES=\
	gc.h\
	../2c/2.out.h\
	../cc/compat.h\
	../cc/cc.h\

T=2
<../cc/mkfile.port
<$APEXPROOT/sys/src/cmd/mkone
