.TH "unknownt" 3 "Mar 12, 2023"
.SH UnknownType
.PP
.B
Inherits from:

Exception
.PP
.B
Maturity Index:

Experimental
.SH Class Description
.PP
This is a subclass to signal an unknown type descriptor, specifically for the 
.B
AsciiFiler
class\&.  If a filer scans a decriptor type string that it cannot handle, then it will signal the 
.B
UnknownType
exception\&.
.SH Method types
.SH Methods
.PP 
typeDesc
.RS 1
- (
char
)
.B
typeDesc
.RE
.PP
Returns the unknown type descriptor\&.
.PP 
typeDesc:
.RS 1
-
.B
typeDesc
:(char)
.I
c
.RE
.PP
Sets the unknown type descriptor\&.
