</$objtype/mkfile

APEXPROOT=../../..
LIB=$APEXPROOT/$objtype/lib/libvterm.a

OFILES=\
	encoding.$O\
	parser.$O\
	pen.$O\
	screen.$O\
	state.$O\
	unicode.$O\
	vterm.$O\

HFILES=\
	vterm.h\
	vterm_keycodes.h\
	vterm_internal.h\
	vtcompat.h\
	utf8.h\
	rect.h\

CFLAGS=$CFLAGS -I.

<$APEXPROOT/sys/src/cmd/mksyslib

# Install the public headers so vts (engine.c) can find them.
installheaders:V:
	cp vterm.h vterm_keycodes.h vtcompat.h $APEXPROOT/sys/include
