/* config.h.  Generated by configure.  */
/* conf.in.  Generated from configure.in by autoheader.  */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

#include "/sys/include/ape/config.h"

/* Define to the GNU M4 executable name. */
#define M4 "/$M/bin/ape/m4"

/* Name of package */
#define PACKAGE "flex"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "flex-help@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "the fast lexical analyser generator"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "the fast lexical analyser generator 2.5.35"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "flex"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.5.35"

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Version number of package */
#define VERSION "2.5.35"

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
/* #undef YYTEXT_POINTER */



