/*
 * curl_config.h for APExp -- lib/curl_config.h.in answered by hand.
 *
 * curl does use a config header: configure.ac line 40 is
 * AC_CONFIG_HEADERS(lib/curl_config.h). LibreSSL beside it does not,
 * which is why only this package has one.
 *
 * This is a FIRST CUT, generated by walking the 300 #undef names in the
 * template and answering each one mechanically:
 *
 *   HAVE_<header>_H   defined if sys/include/ape has that header
 *   HAVE_<func>       defined if libap defines the symbol, or an APE
 *                     header declares it
 *   SIZEOF_*          amd64: int 4, long 4, long long 8, pointer-sized
 *                     types 8. Note long is 32-bit here, which is the
 *                     usual source of trouble.
 *   everything else   left undefined
 *
 * Mechanical means wrong in places. A configure probe compiles and
 * links; this only looks for a definition, so a function that exists
 * but does not work, or one behind the wrong feature-test macro, will
 * be claimed here. Expect to correct entries as the build reports them,
 * the way sys/src/ape/cmd/core/config.h was corrected.
 */

#ifndef APEXP_CURL_CONFIG_H
#define APEXP_CURL_CONFIG_H

/* Values. */
#define CURL_CA_BUNDLE               "/sys/lib/ape/ssl/cert.pem"
#define CURL_DEFAULT_SSL_BACKEND     "openssl"
#define CURL_OS                      "plan9-apexp"
#define GETHOSTNAME_TYPE_ARG2        size_t
#define LT_OBJDIR                    ".libs/"
#define PACKAGE                      "curl"
#define PACKAGE_BUGREPORT            "a suitable curl mailing list: https://curl.se/mail/"
#define PACKAGE_NAME                 "curl"
#define PACKAGE_STRING               "curl 8.21.0"
#define PACKAGE_TARNAME              "curl"
#define PACKAGE_URL                  ""
#define PACKAGE_VERSION              "8.21.0"
#define SIZEOF_CURL_OFF_T            8
#define SIZEOF_INT                   4
#define SIZEOF_LONG                  4
#define SIZEOF_LONG_LONG             8
#define SIZEOF_OFF_T                 8
#define SIZEOF_SHORT                 2
#define SIZEOF_SIZE_T                8
#define SIZEOF_TIME_T                8
#define VERSION                      "8.21.0"

/* Headers APE has. */
#define HAVE_ARPA_INET_H                 1	/* arpa/inet.h */
#define HAVE_DIRENT_H                    1	/* dirent.h */
#define HAVE_DLFCN_H                     1	/* dlfcn.h */
#define HAVE_FCNTL_H                     1	/* fcntl.h */
#define HAVE_INTTYPES_H                  1	/* inttypes.h */
#define HAVE_LIBGEN_H                    1	/* libgen.h */
#define HAVE_LOCALE_H                    1	/* locale.h */
#define HAVE_NETDB_H                     1	/* netdb.h */
#define HAVE_NETINET_IN_H                1	/* netinet/in.h */
#define HAVE_NETINET_TCP_H               1	/* netinet/tcp.h */
#define HAVE_NET_IF_H                    1	/* net/if.h */
#define HAVE_POLL_H                      1	/* poll.h */
#define HAVE_PWD_H                       1	/* pwd.h */
#define HAVE_STDATOMIC_H                 1	/* stdatomic.h */
#define HAVE_STDBOOL_H                   1	/* stdbool.h */
#define HAVE_STDINT_H                    1	/* stdint.h */
#define HAVE_SYS_IOCTL_H                 1	/* sys/ioctl.h */
#define HAVE_SYS_PARAM_H                 1	/* sys/param.h */
#define HAVE_SYS_RESOURCE_H              1	/* sys/resource.h */
#define HAVE_SYS_SELECT_H                1	/* sys/select.h */
#define HAVE_SYS_STAT_H                  1	/* sys/stat.h */
#define HAVE_SYS_TYPES_H                 1	/* sys/types.h */
#define HAVE_SYS_UN_H                    1	/* sys/un.h */
#define HAVE_TERMIOS_H                   1	/* termios.h */
#define HAVE_UNISTD_H                    1	/* unistd.h */
#define HAVE_UTIME_H                     1	/* utime.h */
#define HAVE_ZSTD_H                      1	/* zstd.h */

/* Functions found in libap or declared by an APE header. */
#define CURL_DISABLE_LDAP                1	/* required here */
#define CURL_DISABLE_LDAPS               1	/* required here */
#define HAVE_ALARM                       1	/* APE header */
#define HAVE_ARC4RANDOM                  1	/* APE header */
#define HAVE_BASENAME                    1	/* APE header */
#define HAVE_FCNTL                       1	/* APE header */
#define HAVE_FNMATCH                     1	/* libap */
#define HAVE_FREEADDRINFO                1	/* APE header */
#define HAVE_FSEEKO                      1	/* libap */
#define HAVE_GETADDRINFO                 1	/* APE header */
#define HAVE_GETEUID                     1	/* APE header */
#define HAVE_GETHOSTBYNAME_R             1	/* libap */
#define HAVE_GETHOSTNAME                 1	/* APE header */
#define HAVE_GETPEERNAME                 1	/* APE header */
#define HAVE_GETPPID                     1	/* APE header */
#define HAVE_GETPWUID                    1	/* APE header */
#define HAVE_GETPWUID_R                  1	/* libap */
#define HAVE_GETRLIMIT                   1	/* APE header */
#define HAVE_GETSOCKNAME                 1	/* APE header */
#define HAVE_GETTIMEOFDAY                1	/* APE header */
#define HAVE_GMTIME_R                    1	/* APE header */
#define HAVE_IF_NAMETOINDEX              1	/* libap */
#define HAVE_INET_NTOP                   1	/* APE header */
#define HAVE_INET_PTON                   1	/* APE header */
#define HAVE_LOCALTIME_R                 1	/* APE header */
#define HAVE_MEMRCHR                     1	/* libap */
#define HAVE_OPENDIR                     1	/* APE header */
#define HAVE_PIPE                        1	/* APE header */
#define HAVE_PIPE2                       1	/* APE header */
#define HAVE_POLL                        1	/* APE header */
#define HAVE_REALPATH                    1	/* libap */
#define HAVE_RECV                        1	/* APE header */
#define HAVE_SCHED_YIELD                 1	/* APE header */
#define HAVE_SELECT                      1	/* APE header */
#define HAVE_SEND                        1	/* APE header */
#define HAVE_SENDMSG                     1	/* libap */
#define HAVE_SETLOCALE                   1	/* APE header */
#define HAVE_SETRLIMIT                   1	/* APE header */
#define HAVE_SIGACTION                   1	/* APE header */
#define HAVE_SIGNAL                      1	/* APE header */
#define HAVE_SIGSETJMP                   1	/* APE header */
#define HAVE_SOCKET                      1	/* APE header */
#define HAVE_SOCKETPAIR                  1	/* APE header */
#define HAVE_STDIO_H                     1	/* required here */
#define HAVE_STDLIB_H                    1	/* required here */
#define HAVE_STRCASECMP                  1	/* APE header */
#define HAVE_STRERROR_R                  1	/* libap */
#define HAVE_STRINGS_H                   1	/* required here */
#define HAVE_STRING_H                    1	/* required here */
#define HAVE_UTIME                       1	/* APE header */
#define HAVE_UTIMES                      1	/* APE header */
#define STDC_HEADERS                     1	/* required here */
#define USE_IPV6                         1	/* required here */
#define USE_OPENSSL                      1	/* required here */

/* Left undefined. */
/* #undef CURL_CA_FALLBACK             */	/* left off */
/* #undef CURL_CA_NATIVE               */	/* left off */
/* #undef CURL_CA_PATH                 */	/* left off */
/* #undef CURL_CA_SEARCH_SAFE          */	/* left off */
/* #undef CURL_DEBUG_GLOBAL_MEM        */	/* left off */
/* #undef CURL_DISABLE_ALTSVC          */	/* left off */
/* #undef CURL_DISABLE_AWS             */	/* left off */
/* #undef CURL_DISABLE_BASIC_AUTH      */	/* left off */
/* #undef CURL_DISABLE_BEARER_AUTH     */	/* left off */
/* #undef CURL_DISABLE_BINDLOCAL       */	/* left off */
/* #undef CURL_DISABLE_CA_SEARCH       */	/* left off */
/* #undef CURL_DISABLE_COOKIES         */	/* left off */
/* #undef CURL_DISABLE_DICT            */	/* left off */
/* #undef CURL_DISABLE_DIGEST_AUTH     */	/* left off */
/* #undef CURL_DISABLE_DOH             */	/* left off */
/* #undef CURL_DISABLE_FILE            */	/* left off */
/* #undef CURL_DISABLE_FORM_API        */	/* left off */
/* #undef CURL_DISABLE_FTP             */	/* left off */
/* #undef CURL_DISABLE_GETOPTIONS      */	/* left off */
/* #undef CURL_DISABLE_GOPHER          */	/* left off */
/* #undef CURL_DISABLE_HEADERS_API     */	/* left off */
/* #undef CURL_DISABLE_HSTS            */	/* left off */
/* #undef CURL_DISABLE_HTTP            */	/* left off */
/* #undef CURL_DISABLE_HTTP_AUTH       */	/* left off */
/* #undef CURL_DISABLE_IMAP            */	/* left off */
/* #undef CURL_DISABLE_IPFS            */	/* left off */
/* #undef CURL_DISABLE_KERBEROS_AUTH   */	/* left off */
/* #undef CURL_DISABLE_LIBCURL_OPTION  */	/* left off */
/* #undef CURL_DISABLE_MIME            */	/* left off */
/* #undef CURL_DISABLE_MQTT            */	/* left off */
/* #undef CURL_DISABLE_NEGOTIATE_AUTH  */	/* left off */
/* #undef CURL_DISABLE_NETRC           */	/* left off */
/* #undef CURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG */	/* left off */
/* #undef CURL_DISABLE_PARSEDATE       */	/* left off */
/* #undef CURL_DISABLE_POP3            */	/* left off */
/* #undef CURL_DISABLE_PROGRESS_METER  */	/* left off */
/* #undef CURL_DISABLE_PROXY           */	/* left off */
/* #undef CURL_DISABLE_RTSP            */	/* left off */
/* #undef CURL_DISABLE_SHA512_256      */	/* left off */
/* #undef CURL_DISABLE_SHUFFLE_DNS     */	/* left off */
/* #undef CURL_DISABLE_SMTP            */	/* left off */
/* #undef CURL_DISABLE_SOCKETPAIR      */	/* left off */
/* #undef CURL_DISABLE_TELNET          */	/* left off */
/* #undef CURL_DISABLE_TFTP            */	/* left off */
/* #undef CURL_DISABLE_VERBOSE_STRINGS */	/* left off */
/* #undef CURL_DISABLE_WEBSOCKETS      */	/* left off */
/* #undef CURL_ENABLE_NTLM             */	/* left off */
/* #undef CURL_ENABLE_SMB              */	/* left off */
/* #undef CURL_EXTERN_SYMBOL           */	/* left off */
/* #undef CURL_KRB5_VERSION            */	/* left off */
/* #undef CURL_WITH_MULTI_SSL          */	/* not on this platform */
/* #undef HAVE_ACCEPT4                 */	/* not in libap */
/* #undef HAVE_ATOMIC                  */	/* not in libap */
/* #undef HAVE_BOOL_T                  */	/* not in libap */
/* #undef HAVE_BROTLI                  */	/* not in libap */
/* #undef HAVE_BROTLI_DECODE_H         */	/* no such APE header */
/* #undef HAVE_BUILTIN_AVAILABLE       */	/* not in libap */
/* #undef HAVE_CLOCK_GETTIME_MONOTONIC */	/* not in libap */
/* #undef HAVE_CLOCK_GETTIME_MONOTONIC_RAW */	/* not in libap */
/* #undef HAVE_CLOSESOCKET             */	/* not in libap */
/* #undef HAVE_CLOSESOCKET_CAMEL       */	/* not in libap */
/* #undef HAVE_DECL_FSEEKO             */	/* not in libap */
/* #undef HAVE_DES_ECB_ENCRYPT         */	/* not in libap */
/* #undef HAVE_EVENTFD                 */	/* not in libap */
/* #undef HAVE_FCNTL_O_NONBLOCK        */	/* not in libap */
/* #undef HAVE_FSETXATTR               */	/* not on this platform */
/* #undef HAVE_FSETXATTR_5             */	/* not in libap */
/* #undef HAVE_FSETXATTR_6             */	/* not in libap */
/* #undef HAVE_GETADDRINFO_THREADSAFE  */	/* not in libap */
/* #undef HAVE_GETHOSTBYNAME_R_3       */	/* not in libap */
/* #undef HAVE_GETHOSTBYNAME_R_5       */	/* not in libap */
/* #undef HAVE_GETHOSTBYNAME_R_6       */	/* not in libap */
/* #undef HAVE_GETIFADDRS              */	/* not in libap */
/* #undef HAVE_GETPASS_R               */	/* not in libap */
/* #undef HAVE_GLIBC_STRERROR_R        */	/* not in libap */
/* #undef HAVE_GNUTLS_SRP              */	/* not in libap */
/* #undef HAVE_GSASL_H                 */	/* no such APE header */
/* #undef HAVE_GSSAPI                  */	/* not on this platform */
/* #undef HAVE_GSSAPI_GSSAPI_GENERIC_H */	/* no such APE header */
/* #undef HAVE_GSSAPI_GSSAPI_H         */	/* no such APE header */
/* #undef HAVE_GSSAPI_GSSAPI_KRB5_H    */	/* no such APE header */
/* #undef HAVE_GSSGNU                  */	/* not in libap */
/* #undef HAVE_IDN2_H                  */	/* no such APE header */
/* #undef HAVE_IFADDRS_H               */	/* no such APE header */
/* #undef HAVE_IOCTLSOCKET             */	/* not in libap */
/* #undef HAVE_IOCTLSOCKET_CAMEL       */	/* not in libap */
/* #undef HAVE_IOCTLSOCKET_CAMEL_FIONBIO */	/* not in libap */
/* #undef HAVE_IOCTLSOCKET_FIONBIO     */	/* not in libap */
/* #undef HAVE_IOCTL_FIONBIO           */	/* not in libap */
/* #undef HAVE_IOCTL_SIOCGIFADDR       */	/* not in libap */
/* #undef HAVE_IO_H                    */	/* no such APE header */
/* #undef HAVE_LBER_H                  */	/* no such APE header */
/* #undef HAVE_LDAP_H                  */	/* not on this platform */
/* #undef HAVE_LDAP_INIT_FD            */	/* not in libap */
/* #undef HAVE_LDAP_SSL                */	/* not in libap */
/* #undef HAVE_LDAP_SSL_H              */	/* no such APE header */
/* #undef HAVE_LDAP_URL_PARSE          */	/* not in libap */
/* #undef HAVE_LIBBROTLIDEC            */	/* not on this platform */
/* #undef HAVE_LIBIDN2                 */	/* not in libap */
/* #undef HAVE_LIBPSL_H                */	/* no such APE header */
/* #undef HAVE_LIBSSH                  */	/* not in libap */
/* #undef HAVE_LIBSSH2                 */	/* not in libap */
/* #undef HAVE_LIBSSL                  */	/* not in libap */
/* #undef HAVE_LIBZ                    */	/* not on this platform */
/* #undef HAVE_LIBZSTD                 */	/* not in libap */
/* #undef HAVE_LINUX_TCP_H             */	/* no such APE header */
/* #undef HAVE_MACH_ABSOLUTE_TIME      */	/* not in libap */
/* #undef HAVE_MBEDTLS_DES_CRYPT_ECB   */	/* not in libap */
/* #undef HAVE_MEMSET_EXPLICIT         */	/* not in libap */
/* #undef HAVE_MEMSET_S                */	/* not in libap */
/* #undef HAVE_NETINET_IN6_H           */	/* no such APE header */
/* #undef HAVE_NETINET_UDP_H           */	/* no such APE header */
/* #undef HAVE_NGHTTP2_NGHTTP2_H       */	/* no such APE header */
/* #undef HAVE_NGHTTP3_NGHTTP3_H       */	/* no such APE header */
/* #undef HAVE_NGTCP2_NGTCP2_CRYPTO_H  */	/* no such APE header */
/* #undef HAVE_NGTCP2_NGTCP2_H         */	/* no such APE header */
/* #undef HAVE_OPENSSL_CRYPTO_H        */	/* no such APE header */
/* #undef HAVE_OPENSSL_ERR_H           */	/* no such APE header */
/* #undef HAVE_OPENSSL_PEM_H           */	/* no such APE header */
/* #undef HAVE_OPENSSL_RSA_H           */	/* no such APE header */
/* #undef HAVE_OPENSSL_SRP             */	/* not in libap */
/* #undef HAVE_OPENSSL_SSL_H           */	/* no such APE header */
/* #undef HAVE_POSIX_STRERROR_R        */	/* not in libap */
/* #undef HAVE_PROTO_BSDSOCKET_H       */	/* no such APE header */
/* #undef HAVE_QUICHE_CONN_SET_QLOG_FD */	/* not in libap */
/* #undef HAVE_QUICHE_H                */	/* no such APE header */
/* #undef HAVE_SA_FAMILY_T             */	/* not in libap */
/* #undef HAVE_SENDMMSG                */	/* not in libap */
/* #undef HAVE_SIGINTERRUPT            */	/* not in libap */
/* #undef HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID */	/* not in libap */
/* #undef HAVE_SSL_SET0_WBIO           */	/* not in libap */
/* #undef HAVE_SSL_SET1_ECH_CONFIG_LIST */	/* not in libap */
/* #undef HAVE_SSL_SET_QUIC_TLS_CBS    */	/* not in libap */
/* #undef HAVE_SSL_SET_QUIC_USE_LEGACY_CODEPOINT */	/* not in libap */
/* #undef HAVE_STRCMPI                 */	/* not in libap */
/* #undef HAVE_STRICMP                 */	/* not in libap */
/* #undef HAVE_STROPTS_H               */	/* no such APE header */
/* #undef HAVE_STRUCT_SOCKADDR_STORAGE */	/* not in libap */
/* #undef HAVE_STRUCT_TIMEVAL          */	/* not in libap */
/* #undef HAVE_SUSECONDS_T             */	/* not in libap */
/* #undef HAVE_SYS_EVENTFD_H           */	/* no such APE header */
/* #undef HAVE_SYS_FILIO_H             */	/* no such APE header */
/* #undef HAVE_SYS_POLL_H              */	/* no such APE header */
/* #undef HAVE_SYS_SOCKIO_H            */	/* no such APE header */
/* #undef HAVE_SYS_UTIME_H             */	/* no such APE header */
/* #undef HAVE_SYS_XATTR_H             */	/* no such APE header */
/* #undef HAVE_TERMIO_H                */	/* no such APE header */
/* #undef HAVE_THREADS_POSIX           */	/* not in libap */
/* #undef HAVE_TIME_T_UNSIGNED         */	/* not in libap */
/* #undef HAVE_UNICODE_UIDNA_H         */	/* no such APE header */
/* #undef HAVE_UV_H                    */	/* no such APE header */
/* #undef HAVE_WC_DES_ECBENCRYPT       */	/* not in libap */
/* #undef HAVE_WOLFSSL_BIO_NEW         */	/* not in libap */
/* #undef HAVE_WOLFSSL_BIO_SET_SHUTDOWN */	/* not in libap */
/* #undef HAVE_WOLFSSL_CTX_GENERATEECHCONFIG */	/* not in libap */
/* #undef HAVE_WOLFSSL_GET_PEER_CERTIFICATE */	/* not in libap */
/* #undef HAVE_WOLFSSL_SET_QUIC_USE_LEGACY_CODEPOINT */	/* not in libap */
/* #undef HAVE_WOLFSSL_USEALPN         */	/* not in libap */
/* #undef HAVE_WRITABLE_ARGV           */	/* not in libap */
/* #undef HAVE_ZSTD                    */	/* not on this platform */
/* #undef NEED_LBER_H                  */	/* not on this platform */
/* #undef NEED_REENTRANT               */	/* not on this platform */
/* #undef NEED_THREAD_SAFE             */	/* not on this platform */
/* #undef OPENSSL_QUIC_API2            */	/* left off */
/* #undef SIZEOF_CURL_SOCKET_T         */	/* left off */
/* #undef USE_AMISSL                   */	/* left off */
/* #undef USE_APPLE_IDN                */	/* left off */
/* #undef USE_APPLE_SECTRUST           */	/* left off */
/* #undef USE_ARES                     */	/* left off */
/* #undef USE_BACKTRACE                */	/* left off */
/* #undef USE_ECH                      */	/* left off */
/* #undef USE_GNUTLS                   */	/* left off */
/* #undef USE_GSASL                    */	/* left off */
/* #undef USE_HTTPSRR                  */	/* left off */
/* #undef USE_LIBPSL                   */	/* left off */
/* #undef USE_LIBSSH                   */	/* left off */
/* #undef USE_LIBSSH2                  */	/* left off */
/* #undef USE_LIBUV                    */	/* left off */
/* #undef USE_MBEDTLS                  */	/* left off */
/* #undef USE_NGHTTP2                  */	/* left off */
/* #undef USE_NGHTTP3                  */	/* left off */
/* #undef USE_NGTCP2                   */	/* left off */
/* #undef USE_OPENLDAP                 */	/* left off */
/* #undef USE_PROXY_HTTP3              */	/* left off */
/* #undef USE_QUICHE                   */	/* left off */
/* #undef USE_RESOLV_ARES              */	/* left off */
/* #undef USE_RESOLV_THREADED          */	/* left off */
/* #undef USE_RUSTLS                   */	/* left off */
/* #undef USE_SCHANNEL                 */	/* left off */
/* #undef USE_SSLS_EXPORT              */	/* left off */
/* #undef USE_TLS_SRP                  */	/* left off */
/* #undef USE_UNIX_SOCKETS             */	/* left off */
/* #undef USE_WATT32                   */	/* not on this platform */
/* #undef USE_WIN32_CRYPTO             */	/* left off */
/* #undef USE_WIN32_IDN                */	/* left off */
/* #undef USE_WIN32_LDAP               */	/* left off */
/* #undef USE_WINDOWS_SSPI             */	/* left off */
/* #undef USE_WOLFSSL                  */	/* left off */
/* #undef _FILE_OFFSET_BITS            */	/* left off */
/* #undef _LARGE_FILES                 */	/* left off */

#endif /* APEXP_CURL_CONFIG_H */
