</$objtype/mkfile
APEXPROOT=../../../../../..
T=5
OFILES=\
	5c_vla.$O\
	cgen.$O\
	enam.$O\
	list.$O\
	machcap.$O\
	mul.$O\
	peep.$O\
	pgen.$O\
	pswt.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\

<../mkcompiler



