</$objtype/mkfile
APEXPROOT=../../../../..

TARG=	\
	msgfmt\
	msgmerge\
	xgettext\
	autopoint

PARSEROBJS=	\
	poparser.$O\
	poparser_sysdep.$O\
	StringEscape.$O

BIN=$APEXPROOT/$objtype/bin/ape

<$APEXPROOT/sys/src/cmd/mkmany

GETTEXTSRC=../../../external/gettext


CC=pcc
CFLAGS=-Fw -B


%.$O: $GETTEXTSRC/src/%.c
	$CC $CFLAGS $GETTEXTSRC/src/$stem.c

$O.%: %.$O $PARSEROBJS
	$CC -o $target $prereq








