</$objtype/mkfile
APEXPROOT=../../../../..
TARG=	\
#gettext-runtime/src \
      	gettext\
      	ngettext\
      	envsubst\
#gettext-tools/src \
      	msgattrib\
		msgcat\
		msgcmp\
		msgcomm\
		msgconv\
		msgen\
		msgexec\
		msgfilter\
		msgfmt\
		msggrep\
		msginit\
		msgmerge\
		msgunfmt\
		msguniq\
      	xgettext\
      	recode-sr-latin
#gettext-tools/misc \
#      	gettextize\
#      	autopoint\

GNULIB_OBJECTS=	\
		basename-lgpl.$O\
		c-strstr.$O\
		c-strcasecmp.$O\
		c-strncasecmp.$O\
		c32iscntrl.$O\
		c32width.$O\
		c32isalnum.$O\
		c32isspace.$O\
		clean-temp.$O\
		closeout.$O\
		error.$O\
		error-progname.$O\
		exitfail.$O\
		fwriteerror.$O\
		getprogname.$O\
		lc-charset-dispatch.$O\
		malloca.$O\
		mbchar.$O\
		mbtowc-lock.$O\
		mbrtoc32.$O\
		mbslen.$O\
		mbsinit.$O\
		mbsstr.$O\
		mbszero.$O\
		mempcpy.$O\
		mbuiter.$O\
		mkdtemp.$O\
		progname.$O\
		propername.$O\
		progreloc.$O\
		reallocarray.$O\
		strnlen1.$O\
		striconv.$O\
		trim.$O\
		xalloc-die.$O\
		xerror.$O\
		xmalloc.$O\
		xstriconv.$O\
# gnulib-lib/unictype\
		ctype_alnum.$O\
		ctype_cntrl.$O\
		ctype_space.$O\
# gnulib-lib/uniwidth\
		width.$O

# weird thing: some things are not included when linked from library...

LIB=$APEXPROOT/$objtype/lib/ape/libintl.a\
	$APEXPROOT/$objtype/lib/ape/libiconv.a\
	libgnulib.a$O

BIN=$APEXPROOT/$objtype/bin/ape
HFILES=$APEXPROOT/sys/include/ape/libintl.h

<$APEXPROOT/sys/src/cmd/mkmany

GETTEXTSRC=../../../external/gettext

CC=pcc
LD=pcc
DEFS= 	-DLOCALEDIR="/sys/lib/ape/locale" -DBISON_LOCALEDIR="/sys/lib/ape/locale" -DLIBDIR="/$objtype/lib/ape"\
		-DEXEEXT="" -DPROJECTSDIR="." -DGETTEXTJAR="/sys/lib/ape/gettext" -DGETTEXTDATADIR="/sys/lib/ape/gettext"\
		-Drpl_optarg=optarg -Drpl_getopt=getopt -Drpl_optind=optind -Drpl_getopt_long=getopt_long -Drpl_malloc=malloc\
		-Drpl_realloc=realloc -Drpl_calloc=calloc -Drpl_free=free -Drpl_rmdir=rmdir -Drpl_open=open\
		-DENABLE_NLS -DHAVE_ICONV -DGNULIB_MBRTOC32_REGULAR -DGNULIB_MBRTOWC_SINGLE_THREAD -DPLAN9

RINCLUDE= 	-I$GETTEXTSRC/gettext-runtime/src -I$GETTEXTSRC/gettext-runtime\
			-I$GETTEXTSRC/gettext-runtime/gnulib-lib -I$GETTEXTSRC/gettext-runtime/intl

TINCLUDE= 	-I$GETTEXTSRC/gettext-tools -I$GETTEXTSRC/gettext-tools/gnulib-lib\
		  	-I$GETTEXTSRC/libtextstyle/lib -I$GETTEXTSRC/gnulib-local/lib\
			-I$GETTEXTSRC/gettext-tools/libgrep $RINCLUDE

CFLAGS=-c -B -DHAVE_CONFIG_H -D_POSIX_SOURCE -D_BSD_EXTENSION $DEFS

hash-string.$O: $GETTEXTSRC/gettext-runtime/intl/hash-string.c
	$CC $CFLAGS $RINCLUDE $GETTEXTSRC/gettext-runtime/intl/hash-string.c

%.$O: $GETTEXTSRC/gettext-runtime/src/%.c
	$CC $CFLAGS $RINCLUDE $GETTEXTSRC/gettext-runtime/src/$stem.c

%.$O: $GETTEXTSRC/gettext-tools/src/%.c
	$CC $CFLAGS $TINCLUDE $GETTEXTSRC/gettext-tools/src/$stem.c

%.$O: $GETTEXTSRC/gettext-tools/gnulib-lib/%.c
	$CC $CFLAGS $TINCLUDE $GETTEXTSRC/gettext-tools/gnulib-lib/$stem.c

%.$O: $GETTEXTSRC/gettext-tools/gnulib-lib/unictype/%.c
	$CC $CFLAGS $TINCLUDE $GETTEXTSRC/gettext-tools/gnulib-lib/unictype/$stem.c

%.$O: $GETTEXTSRC/gettext-tools/gnulib-lib/uniwidth/%.c
	$CC $CFLAGS $TINCLUDE $GETTEXTSRC/gettext-tools/gnulib-lib/uniwidth/$stem.c

libgnulib.a$O:V:	$GNULIB_OBJECTS
					ar vu libgnulib.a$O $GNULIB_OBJECTS

$O.msgfmt:V: 	msgfmt.$O write-mo.$O write-java.$O write-csharp.$O write-resources.$O\
				write-tcl.$O write-qt.$O write-desktop.$O write-xml.$O hash-string.$O $LIB
				$LD -o $target $prereq

$O.msgcmp:V: 	msgcmp.$O msgl-fsearch.$O $LIB
				$LD -o $target $prereq

$O.msgunfmt:V:	msgunfmt.$O read-mo.$O read-java.$O read-csharp.$O read-resources.$O\
				read-tcl.$O hash-string.$O $LIB
				$LD -o $target $prereq


install:V:


