</$objtype/mkfile
APEXPROOT=../../../../../
LIB=$APEXPROOT/$objtype/lib/ape/libiconv.a

OFILES=	\
# lib\
		iconv.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

ICONVSRC=../../../external/libiconv/src

CC=pcc
LD=pcc
CFLAGS=-c -I$APEXPROOT/sys/include/ape -I. -I$ICONVSRC/lib -DEILSEQ=68 \
		-D_POSIX_SOURCE -DPLAN9

%.$O: $ICONVSRC/%.c
	$CC $CFLAGS $ICONVSRC/$stem.c

install:V:
	cp iconv.h $APEXPROOT/sys/include/ape/
	cp charmaps.h $APEXPROOT/sys/include/ape/
	mkdir -p $APEXPROOT/sys/include/ape/charmaps
	dircp $ICONVSRC/include/charmaps $APEXPROOT/sys/include/ape/charmaps

nuke:V:
	mk clean
	rm -f $LIB
	rm $APEXPROOT/sys/include/ape/iconv.h
	rm $APEXPROOT/sys/include/ape/charmaps.h
	rm -rf $APEXPROOT/sys/include/ape/charmaps

