</$objtype/mkfile
LIB=/$objtype/lib/ape/libiconv.a

OFILES=	\
# lib\
		iconv.$O\

</sys/src/cmd/mksyslib

ICONVSRC=../../../external/libiconv/src

CC=pcc
LD=pcc
CFLAGS=-c -I. -I$ICONVSRC/lib -DEILSEQ=68 \
		-D_POSIX_SOURCE -DPLAN9

%.$O: $ICONVSRC/%.c
	$CC $CFLAGS $ICONVSRC/$stem.c

install:V:
	cp iconv.h /sys/include/ape/
	cp charmaps.h /sys/include/ape/
	mkdir -p /sys/include/ape/charmaps
	dircp $ICONVSRC/include/charmaps /sys/include/ape/charmaps

nuke:V:
	mk clean
	rm -f $LIB
	rm /sys/include/ape/iconv.h
	rm /sys/include/ape/charmaps.h
	rm -rf /sys/include/ape/charmaps

