BUILTINS=
NPROC=3
</$objtype/mkfile

c = frame.c
s = label.s
o = ${c:%.c=%.$O} ${s:%.s=%.$O}
l = ../libtask.a
lo= ${o:%=$l(%)}

%.$O:	%.c
	c++/$CC -I. -I.. $stem.c
%.$O:	../task.h label.h

%.$O:	%.s
	$AS $stem.s

lib:V:	$l
$l(%.$O):N:	%.$O
$l:	$lo
	names=`{membername $newprereq}
	ar vu $target $names
	rm $names

install:V: $o
	ar vu /$objtype/lib/c++/libtask.a $o
	cp label.h /$objtype/include/c++

clean:V:
	rm -f *.[$OS] [$OS].out y.tab.?
