APEXPROOT=../../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libmp.a

SFILES=\
	mpvecadd.s\
	mpvecsub.s\
	mpvecdigmuladd.s\
	mpvecdigmulsub.s\

HFILES=\
	$APEXPROOT/sys/include/ape/mp.h\
	$APEXPROOT/sys/src/libmp/port/dat.h

OFILES=${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

<$APEXPROOT/sys/src/cmd/mksyslib

%.$O:	/sys/src/libmp/power/%.s
	$AS /sys/src/libmp/power/$stem.s
