APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

SAMUSRC=$APEXPROOT/sys/src/external/samurai

BIN=$APEXPROOT/$objtype/bin/ape
TARG=samu

OFILES=\
	build.$O\
	deps.$O\
	env.$O\
	graph.$O\
	htab.$O\
	log.$O\
	parse.$O\
	samu.$O\
	scan.$O\
	tool.$O\
	tree.$O\
	util.$O

<$APEXPROOT/sys/src/cmd/mkone

CFLAGS=-FVp -c -I$SAMUSRC

%.$O: $SAMUSRC/%.c
	$CC $CFLAGS $SAMUSRC/$stem.c


install:V:
	cp $SAMUSRC/samu.1 $APEXPROOT/sys/man/1/samu




