</$objtype/mkfile

CFLAGS=-FV -I.
LIB=/$objtype/lib/c++/libC.a
OFILES=Pool_std.$O std_exc.$O std_find.$O std_in.$O \
	std_misc.$O std_put.$O std_str.$O std_win.$O \
	std_wput.$O std_wstr.$O 

</sys/src/cmd/mksyslib

