APEXPROOT=../../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libsec.a

HFILES=$APEXPROOT/sys/include/ape/libsec.h

OFILES=\

UPDATE=mkfile $HFILES

<$APEXPROOT/sys/src/cmd/mksyslib
