APEXPROOT=../../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
# libutf\
	rune.$O\
	runestrcat.$O\
	runestrchr.$O\
	runestrcmp.$O\
	runestrcpy.$O\
	runestrdup.$O\
	runestrlen.$O\
	runestrecpy.$O\
	runestrncat.$O\
	runestrncmp.$O\
	runestrncpy.$O\
	runestrrchr.$O\
	runestrstr.$O\
	runetype.$O\
	utfecpy.$O\
	utflen.$O\
	utfnlen.$O\
	utfrrune.$O\
	utfrune.$O\
	utfutf.$O\
# sbase libutf\
	fgetrune.$O\
	fputrune.$O\
	isalnumrune.$O\
	isblankrune.$O\
	iscntrlrune.$O\
	isdigitrune.$O\
	isgraphrune.$O\
	isprintrune.$O\
	ispunctrune.$O\
	istitlerune.$O\
	isxdigitrune.$O\
	runecmp.$O\
	utftorunestr.$O\
	charntorune.$O\

HFILES=\
	$APEXPROOT/sys/include/ape/utf.h\

UPDATE=\
	mkfile\
	${OFILES:%.$O=%.c}\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=-c -D_POSIX_SOURCE -D_PLAN9_SOURCE -D_BSD_EXTENSION -I../include
