APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
#	aio.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE\
	-I../include
