</$objtype/mkfile

LIB=/$objtype/lib/libnpe_portmidi.a
CFLAGS=$CFLAGS -p -I../include/npe -D__plan9__ -D__${objtype}__

HFILES=\

OFILES=\
	pm.$O\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/386/%}\

</sys/src/cmd/mksyslib
