APEXPROOT=../../../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libap.a

FILES=\
	mpaux\
	mpfmt\
	strtomp\
	mptobe\
	mptober\
	mptole\
	mptolel\
	betomp\
	letomp\
	mpadd\
	mpsub\
	mpcmp\
	mpsel\
	mpfactorial\
	mpmul\
	mpleft\
	mpright\
	mpvecadd\
	mpvecsub\
	mpvecdigmuladd\
	mpveccmp\
	mpvectscmp\
	mpdigdiv\
	mpdiv\
	mpexp\
	mpmod\
	mpmodop\
	mpextendedgcd\
	mpinvert\
	mprand\
	mpnrand\
	crt\
	mptoi\
	mptoui\
	mptov\
	mptouv\
	mpfield\
	cnfield\
	gmfield\
	mplogic\

ALLOFILES=${FILES:%=%.$O}

# cull things in the per-machine directories from this list
OFILES=	`{rfork en; \
	if(~ $objtype spim) objtype=mips; \
	rc reduce $O $objtype $ALLOFILES}

HFILES=\
	$APEXPROOT/sys/include/ape/mp.h\
	dat.h\

CFILES=${FILES:%=%.c}

UPDATE=\
	mkfile\
	$HFILES\
	$CFILES\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=-TVwc -+ -D_POSIX_SOURCE -D_PLAN9_SOURCE -I. -I../../plan9

%.$O:	%.c
	$CC $CFLAGS $stem.c
