APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
	mkstemp.$O\
	mktemp.$O\
	tmpfile.$O\
#	musl\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE\
	-D_BSD_EXTENSION -D_PLAN9_SOURCE -I../include
