APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libcroco.a

OFILES=\
	cr-additional-sel.$O\
	cr-attr-sel.$O\
	cr-cascade.$O\
	cr-declaration.$O\
	cr-doc-handler.$O\
	cr-enc-handler.$O\
	cr-fonts.$O\
	cr-input.$O\
	cr-num.$O\
	cr-om-parser.$O\
	cr-parser.$O\
	cr-parsing-location.$O\
	cr-prop-list.$O\
	cr-pseudo.$O\
	cr-rgb.$O\
	cr-sel-eng.$O\
	cr-selector.$O\
	cr-simple-sel.$O\
	cr-statement.$O\
	cr-string.$O\
	cr-style.$O\
	cr-stylesheet.$O\
	cr-term.$O\
	cr-tknzr.$O\
	cr-token.$O\
	cr-utils.$O

<$APEXPROOT/sys/src/cmd/mksyslib

GETTEXTSRC=../../../external/gettext
CROCOSRC=../../../external/gettext/libtextstyle/lib/libcroco

#during building from scratch, the new pcc is not picked up and compilation
#fails on include_next
CC=$APEXPROOT/$objtype/bin/pcc

DEFS=

CFLAGS=-c -B -I. -I$CROCOSRC -I$CROCOSRC/..\
	-I$GETTEXTSRC/libtextstyle -I$GETTEXTSRC/libtextstyle/lib/glib\
	-D_POSIX_SOURCE -D_BSD_SOURCE -DHAVE_CONFIG_H $DEFS

%.$O: $CROCOSRC/%.c
	$CC $CFLAGS $CROCOSRC/$stem.c







