APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a
OFILES=\
	poll.$O\


UPDATE=\
	mkfile\
	$APEXPROOT/$objtype/lib/ape/libap.a\
	${OFILES:%.$O=%.c}\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -I$APEXPROOT/sys/include/ape -I$APEXPROOT/$objtype/include/ape\
	-D_POSIX_SOURCE -D_PLAN9_SOURCE -D_BSD_EXTENSION\
	-D_RESEARCH_SOURCE -D_NET_EXTENSION -I../include -I../plan9


