APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

CHCSRC=../../../external/chicken
LIB=$APEXPROOT/$objtype/lib/ape/libchicken.a

TARG=chicken

BIN=$APEXPROOT/$objtype/bin/ape

TARG= 	chicken\
		chicken-do\
		chicken-install\
		chicken-uninstall\
		chicken-status

CHOFILES=\
	chicken.$O\
	batch-driver.$O\
	core.$O\
	optimizer.$O\
	lfa2.$O\
	compiler-syntax.$O\
	scrutinizer.$O\
	support.$O\
	c-platform.$O\
	c-backend.$O\
	user-pass.$O

<$APEXPROOT/sys/src/cmd/mkmany

CC=pcc
LD=pcc
CFLAGS= -c -D_POSIX_SOURCE -I$CHCSRC -DHAVE_CHICKEN_CONFIG_H -DHAVE_ALLOCA_H -DC_BUILDING_CHICKEN\
	-DC_LLP

%.$O: $CHCSRC/%.c
    $CC $CFLAGS $CHCSRC/$stem.c

$O.chicken: $CHOFILES

$O.chicken-do: chicken-do.$O

$O.chicken-install: chicken-install.$O

$O.chicken-uninstall: chicken-uninstall.$O

$O.chicken-status: chicken-status.$O










