APEXPROOT=../../../../..

ARCHES=\
	1c\
	2c\
	5c\
	6c\
	7c\
	8c\
	9c\
	kc\
	qc\
	vc\

install:V:
	# cc.a$O (cc front-end archive) must exist before arch compilers link
	cd $APEXPROOT/sys/src/cmd/cc && mk install
	for(i in $ARCHES) @{
		cd $i
		echo ----$i----
		mk install
	}

clean:V:
	for(i in $ARCHES) @{
		cd $i
		mk clean
	}

nuke:V:
	for(i in $ARCHES) @{
		cd $i
		mk nuke
	}
