APEXPROOT=../../../../..

ARCHES=\
	1c\
	2c\
	5c\
	6c\
	7c\
	8c\
	9c\
	kc\
	qc\
	vc\

install: cc.a$O
	for(i in $ARCHES) @{
		cd $i
		echo ----$i----
		mk install
	}

cc.a$O:V:
	mk -f mkfile.cc

clean:V:
	for(i in $ARCHES) @{
		cd $i
		mk clean
	}

nuke:V:
	for(i in $ARCHES) @{
		cd $i
		mk nuke
	}
