APEXPROOT=../../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libsec.a

FILES=\
	md5block\
	sha1block\

HFILES=$APEXPROOT/sys/include/ape/libsec.h

SFILES=${FILES:%=%.s}

OFILES=${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

<$APEXPROOT/sys/src/cmd/mksyslib

%.$O:	/sys/src/libsec/$objtype/%.s
	$AS $AFLAGS /sys/src/libsec/$objtype/$stem.s
