</$objtype/mkfile

TARG=kl
OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	sched.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	compat.$O\

HFILES=\
	l.h\
	../kc/k.out.h\
	../cc/compat.h\

APEXPROOT=../../../..
BIN=$APEXPROOT/$objtype/bin
<$APEXPROOT/sys/src/cmd/mkone

../kc/enam.c: ../kc/k.out.h
	@ { cd ../kc; mk enam.c }

enam.$O:	../kc/enam.c
	$CC $CFLAGS ../kc/enam.c

compat.$O:	../cc/compat

