APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a
OFILES=\
	locale.$O\
# musl \
	catclose.$O\
	catgets.$O\
#	catopen.$O\
	langinfo.$O\
	strtod_l.$O\
	strfmon.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -I$APEXPROOT/sys/include/ape -I../include\
	-I$APEXPROOT/$objtype/include/ape -D_POSIX_SOURCE
