APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a
OFILES=\
	locale.$O\
# musl \
	__lctrans.$O\
	c_locale.$O\
	catclose.$O\
	catgets.$O\
	catopen.$O\
	iconv.$O\
	iconv_close.$O\
	langinfo.$O\
	strtod_l.$O\
	strfmon.$O\
# stub\
	locale_charset.$O\


<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -I../include -D_POSIX_SOURCE
