APEXPROOT=../../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libmp.a

SFILES=mpvecdigmuladd.s mpvecdigmulsub.s mpvecadd.s mpvecsub.s

HFILES=\
	$APEXPROOT/sys/include/ape/mp.h\
	/sys/src/libmp/port/dat.h

OFILES=${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

<$APEXPROOT/sys/src/cmd/mksyslib

%.$O:	/sys/src/libmp/arm/%.s
	$AS /sys/src/libmp/arm/$stem.s
