APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libglib.a

OFILES=\
	ghash.$O\
	glist.$O\
	gmessages.$O\
	gprimes.$O\
	gstrfuncs.$O\
	gstring.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

GETTEXTSRC=../../../external/gettext
GLIBSRC=../../../external/gettext/libtextstyle/lib/glib

#during building from scratch, the new pcc is not picked up and compilation
#fails on include_next
CC=$APEXPROOT/$objtype/bin/pcc

DEFS=

CFLAGS=-c -B -I. -I$GLIBSRC -I$GLIBSRC/..
		-D_POSIX_SOURCE -D_BSD_SOURCE -DHAVE_CONFIG_H $DEFS

%.$O: $GLIBSRC/%.c
	$CC $CFLAGS $GLIBSRC/$stem.c







