APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libxml.a

OFILES= \
	DOCBparser.$O\
	HTMLparser.$O\
	HTMLtree.$O\
	SAX.$O\
	SAX2.$O\
	buf.$O\
	c14n.$O\
	catalog.$O\
	chvalid.$O\
	debugXML.$O\
	dict.$O\
	encoding.$O\
	entities.$O\
	error.$O\
	globals.$O\
	hash.$O\
	legacy.$O\
	list.$O\
	nanoftp.$O\
	nanohttp.$O\
	parser.$O\
	parserInternals.$O\
	pattern.$O\
	relaxng.$O\
	schematron.$O\
	threads.$O\
	tree.$O\
	trionan.$O\
	uri.$O\
	valid.$O\
	xinclude.$O\
	xlink.$O\
	xmlIO.$O\
	xmlmemory.$O\
	xmlmodule.$O\
	xmlreader.$O\
	xmlregexp.$O\
	xmlsave.$O\
	xmlschemas.$O\
	xmlschemastypes.$O\
	xmlstring.$O\
	xmlunicode.$O\
	xmlwriter.$O\
	xpath.$O\
	xpointer.$O


<$APEXPROOT/sys/src/cmd/mksyslib

GETTEXTSRC=../../../external/gettext
XMLSRC=../../../external/gettext/libtextstyle/lib/libxml

#during building from scratch, the new pcc is not picked up and compilation
#fails on include_next
CC=$APEXPROOT/$objtype/bin/pcc


DEFS= 	-DLIBXML_DOCB_ENABLED -DLIBXML_HTML_ENABLED -DLIBXML_ZLIB_ENABLED\
		-DLIBXML_PUSH_ENABLED -DLIBXML_SAX1_ENABLED -DLIBXML_OUTPUT_ENABLED\
		-DLIBXML_LEGACY_ENABLED -DLIBXML_VALID_ENABLED -DLIBXML_WRITER_ENABLED\
#		-DLIBXML_C14N_ENABLED -DLIBXML_XINCLUDE_ENABLED -DLIBXML_SCHEMAS_ENABLED\
#		-DLIBXML_XPATH_ENABLED -DLIBXML_TREE_ENABLED  -DLIBXML_REGEXP_ENABLED\
		-DLIBXML_ICONV_ENABLED -DLIBXML_READER_ENABLED -DLIBXML_PATTERN_ENABLED\
		-DLIBXML_UNICODE_ENABLED -DLIBXML_EXPR_ENABLED -DLIBXML_CATALOG_ENABLED\
		-DLIBXML_THREAD_ENABLED 

# -DLIBXML_XPTR_ENABLED



CFLAGS=-c -B -I. -I$XMLSRC -I$XMLSRC/.. -I$GETTEXTSRC/libtextstyle\
		-D_POSIX_SOURCE -D_BSD_SOURCE -DHAVE_CONFIG_H $DEFS

%.$O: $XMLSRC/%.c
	$CC $CFLAGS $XMLSRC/$stem.c







