APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libap.a
OFILES=\
	chmod.$O\
	chown.$O\
	fstat.$O\
	lstat.$O\
	stat.$O\
	umask.$O\
	utime.$O\
# stubs\
	fchown-stub.$O\
# hacks\
	fchmod.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=-c -I$APEXPROOT/sys/include/ape -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE -D_RESEARCH_SOURCE -I../plan9 -I../include
