</$objtype/mkfile

APEXPROOT=../../../..

TARG=cpp
OFILES=\
	cpp.$O\
	lex.$O\
	nlist.$O\
	tokens.$O\
	macro.$O\
	eval.$O\
	include.$O\
	hideset.$O\

HFILES=cpp.h

BIN=$APEXPROOT/$objtype/bin
<$APEXPROOT/sys/src/cmd/mkone
