BUILTINS=
</$objtype/mkfile
<../c++mkfile

APEXPROOT=../../../..
CXXSRC=../../external/c++

$O.out:	patch.$O
	$LD $prereq

install:V:	$O.out
	mv $O.out $APEXPROOT/$objtype/bin/c++/patch

installall:V:
	for(objtype in $CPUS)
		mk install

%.$O:	$CXXSRC/patch/%.c
	$CC -w $CXXSRC/patch/$stem.c

clean:V:
	rm -f *.[$OS] [$OS].out y.tab.?

nuke:V: clean
