APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
	clock.$O\
	clock_gettime.$O\
	clock_nanosleep.$O\
	ctime.$O\
	difftime.$O\
	gettimeofday.$O\
	mktime.$O\
	nanosleep.$O\
	sleep.$O\
	time.$O\
	times.$O\
	tzset.$O\
# musl\
	__map_file.$O\
#	asctime.$O\
#	asctime_r.$O\
# hacks\
	strptime.$O\
	timegm.$O\


<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE\
	-D_BSD_EXTENSION -D_PLAN9_SOURCE -I../include
