</$objtype/mkfile

TARG=va
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../vc/v.out.h\
	../cc/compat.h\
	y.tab.h\
	a.h\

YFILES=a.y\

APEXPROOT=../../../..
BIN=$APEXPROOT/$objtype/bin
< $APEXPROOT/sys/src/cmd/mkone
YFLAGS=-D1 -d

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat
