APE=/sys/src/ape
<$APE/config

DIRS=\
	awk\
	base\
	diff\
	expr\
#	gettext\
	lex\
	make\
	patch\
	pax\
	pcregrep\
	pdksh\
	sed\
	yacc

BIN=$APEBIN
</sys/src/cmd/mkmany

all:V:	$DIRS

install:V:	install.dir install.rc

installall:V:	installall.dir

clean:V:	clean.dir

nuke:V:		nuke.dir

%.dir:V:
	for (i in $DIRS) @{
		cd $i
		echo '----'$i'----'
		mk $stem
	}

$DIRS:V:
	for (i in $target) @{
		cd $i
		echo '----'$i'----'
		mk all
	}


