APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
	_envsetup.$O\
	getenv.$O\
	putenv.$O\
#	musl\
	clearenv.$O\
	setenv.$O\
	unsetenv.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE
