APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a
OFILES=\
	execl.$O\
	execle.$O\
	execlp.$O\
	execv.$O\
	execve.$O\
	execvp.$O\
	fork.$O\
	wait.$O\
# hacks\
	posix_spawn.$O\


UPDATE=\
	mkfile\
	$APEXPROOT/$objtype/lib/ape/libap.a\
	${OFILES:%.$O=%.c}\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -D_POSIX_SOURCE -D_PLAN9_SOURCE -D_BSD_EXTENSION\
	-D_RESEARCH_SOURCE -D_NET_EXTENSION -I../include


