</$objtype/mkfile

_CORE_LIBS=\
	ap\
	auth\
	bio\
	draw\
	plumb\
	sec\
	intl\

_CORE_APP_DEPENDENCIES=\
	flex\

_OPTIONAL_LIBS=\
	bz2\
	curses\
	fortran\
	lua\
	lzma\
	pascal\
	pcre2\
#	perl\
	png\
	readline\
	tcl\
	tk\
	xml2\
	z\
	zstd\

DIRS=\
	$_CORE_LIBS\
	$_CORE_APP_DEPENDENCIES\
	$_OPTIONAL_LIBS\


none:V:
	echo mk all, install, installall, clean, or nuke

all clean nuke install installall:V:
	for (i in $DIRS) @{
		cd $i
		mk $target
	}
