</$objtype/mkfile

_CORE_LIBS=\
	ap\
	auth\
	bio\
	draw\
	l\
	plumb\
	sec\

_CORE_APP_DEPENDENCIES=\
	flex\

_OPTIONAL_LIBS=\
	bz2\
	curses\
	edit\
	fortran\
	gettextpo\
#	intl\
	lua\
	lzma\
	pascal\
	pcre2\
	textstyle\
	xml2\
	z\

DIRS=\
	$_CORE_LIBS\
	$_CORE_APP_DEPENDENCIES\
	$_OPTIONAL_LIBS\


none:V:
	echo mk all, install, installall, clean, or nuke

all clean nuke install installall:V:
	for (i in $DIRS) @{
		cd $i
		mk $target
	}
