</$objtype/mkfile

#do we need libl? We don't build Plan9 lex/yacc

_CORE_LIBS=\
	ap\
	auth\
	bio\
	draw\
	plumb\
	sec\
	intl\

_CORE_APP_DEPENDENCIES=\
	flex\

_OPTIONAL_LIBS=\
	bz2\
	curses\
	readline\
	fortran\
	lua\
	lzma\
	pascal\
	pcre2\
	tcl\
	tk\
	z\

DIRS=\
	$_CORE_LIBS\
	$_CORE_APP_DEPENDENCIES\
	$_OPTIONAL_LIBS\


none:V:
	echo mk all, install, installall, clean, or nuke

all clean nuke install installall:V:
	for (i in $DIRS) @{
		cd $i
		mk $target
	}
