APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libmp.a

SFILES=\
	mpvecadd.s\
	mpvecdigmuladd.s\
	mpvecdigmulsub.s\
	mpvecsub.s\
	mpdigdiv.s\

HFILES=\
	$APEXPROOT/sys/include/ape/mp.h\
	../port/dat.h

OFILES=${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

<$APEXPROOT/sys/src/cmd/mksyslib

%.$O:	%.s
	$AS $stem.s
