APEXPROOT=../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libv.a

OFILES=getpass.$O\
	tty.$O\
	rand.$O\
	nrand.$O\
	getfields.$O\
	min.$O\
	max.$O\
	error.$O\
	nap.$O

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=-c

%.$O:	$FAMILY/%.c
	$CC $CFLAGS $prereq
