APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

BIN=$APEXPROOT/$objtype/bin/ape
TARG=wish

TKSRC=$APEXPROOT/sys/src/external/tk
TCLSRC=$APEXPROOT/sys/src/external/tcl

# -DWCHAR=char is load-bearing, not a workaround: do not remove it.
# Tcl defines WCHAR only for Windows and Cygwin -- tclUnixPort.h's
# "typedef unsigned short WCHAR" sits inside #ifdef __CYGWIN__ -- yet
# tclClock.c uses WCHAR unguarded, so without this the file does not
# compile at all. char is also what Tcl itself picks elsewhere on
# non-Windows: see "#define WCHAR char" in generic/tclIOUtil.c. And it
# has to be char rather than wchar_t, because tclClock.c assigns
# getenv's char * straight to a const WCHAR *.
#
# The matching wcscmp/wcslen/wcscpy redirection lives in tclClock.c
# itself, under #ifdef PLAN9. It cannot be done with -D here: that would
# rewrite the declarations in wchar.h as well as the calls, leaving
# "extern int strcmp(const wchar_t *, const wchar_t *)" to collide with
# the real one in string.h.
CFLAGS=\
	-FVp -c\
	-I$TKSRC/generic\
	-I$TKSRC/xlib\
	-I$TKSRC/plan9\
	-I$TCLSRC/generic\
	-I$APEXPROOT/sys/include/ape\
	-I$APEXPROOT/$objtype/include/ape\
	-DHAVE_TCL_CONFIG_H\
	-DPLAN9\
	-DMODULE_SCOPE=/***/\
	-DWCHAR=char\
	-DTK_PLATFORM="plan9"\


LIB=\
	$APEXPROOT/$objtype/lib/ape/libtk.a\
	$APEXPROOT/$objtype/lib/ape/libtcl.a\
	$APEXPROOT/$objtype/lib/ape/libdraw.a\
	$APEXPROOT/$objtype/lib/ape/libpng.a\
	$APEXPROOT/$objtype/lib/ape/libz.a\
	$APEXPROOT/$objtype/lib/ape/libap.a\

OFILES=tkAppInit.$O

<$APEXPROOT/sys/src/cmd/mkone


tkAppInit.$O: $TKSRC/unix/tkAppInit.c
	$CC $CFLAGS $TKSRC/unix/tkAppInit.c

clean:V:
	rm -f *.[$OS] $BIN/$TARG
