</$objtype/mkfile
APEXPROOT=../../../../..

BIN=$APEXPROOT/$objtype/bin/ape
TARG=$BIN/sed

OFILES=	compile.$O\
		debug.$O\
		execute.$O\
		mbcs.$O\
		regexp.$O\
		sed.$O\
		utils.$O\
		version.$O

# lib objs from Makefile
# I think I can comment out a lot of them
LIB_OBJS=\
	copy-acl.$O\
	set-acl.$O\
	acl-errno-valid.$O\
	acl-internal.$O\
	get-permissions.$O\
	set-permissions.$O\
	basename-lgpl.$O\
	binary-io.$O\
	btowc.$O\
	c-ctype.$O\
	c-strcasecmp.$O\
	c-strncasecmp.$O\
	canonicalize-lgpl.$O\
	cloexec.$O\
	close-stream.$O\
	closeout.$O\
	dfa.$O\
	localeinfo.$O\
	dirname-lgpl.$O\
	stripslash.$O\
	dup2.$O\
	error.$O\
	exitfail.$O\
	fcntl.$O\
	fd-hook.$O\
	fpending.$O\
	free.$O\
	fwriting.$O\
	getprogname.$O\
	getrandom.$O\
	dynarray_at_failure.$O\
	dynarray_emplace_enlarge.$O\
	dynarray_finalize.$O\
	dynarray_resize.$O\
	dynarray_resize_clear.$O\
	scratch_buffer_grow.$O\
	scratch_buffer_grow_preserve.$O\
	scratch_buffer_set_array_size.$O\
	hard-locale.$O\
	ialloc.$O\
	localcharset.$O\
	localeconv.$O\
	lock.$O\
	lstat.$O\
	malloca.$O\
	mbrlen.$O\
	mbrtowc.$O\
	memrchr.$O\
	mkdir.$O\
	mkostemp.$O\
	nl_langinfo.$O\
	obstack.$O\
	progname.$O\
	qcopy-acl.$O\
	qset-acl.$O\
	quotearg.$O\
	rawmemchr.$O\
	readlink.$O\
	reallocarray.$O\
	regex.$O\
	rename.$O\
	rmdir.$O\
	se-context.$O\
	se-label.$O\
	se-selinux.$O\
	setlocale_null.$O\
	setlocale-lock.$O\
	stat-time.$O\
	strerror.$O\
	strerror-override.$O\
	tempname.$O\
	threadlib.$O\
	unistd.$O\
	version-etc.$O\
	version-etc-fsf.$O\
	wctob.$O\
	wctype-h.$O\
	xmalloc.$O\
	xalloc-die.$O\


LIB=libgnu.a$O
BIN=$APEXPROOT/$objtype/bin/ape

<$APEXPROOT/sys/src/cmd/mkone

GSEDSRC=../../../external/gsed

#during building from scratch, the new pcc is not picked up and compilation
#fails on include_next
CC=$APEXPROOT/$objtype/bin/pcc

CFLAGS=-c -I. -I$GSEDSRC -I$GSEDSRC/sed -I$GSEDSRC/lib -B -DHAVE_CONFIG_H\
		-DLOCALEDIR="/sys/lib/ape/locale"

%.$O: $GSEDSRC/sed/%.c
	$CC $CFLAGS $GSEDSRC/sed/$stem.c

%.$O: $GSEDSRC/lib/%.c
	$CC $CFLAGS $GSEDSRC/lib/$stem.c

%.$O: $GSEDSRC/lib/malloc/%.c
	$CC $CFLAGS $GSEDSRC/lib/malloc/$stem.c

%.$O: $GSEDSRC/lib/glthread/%.c
	$CC $CFLAGS $GSEDSRC/lib/glthread/$stem.c

libgnu.a$O: $LIB_OBJS
			ar vu libgnu.a$O $LIB_OBJS

install:V:
		cp $GSEDSRC/doc/sed.1 $APEXPROOT/sys/man/1/sed
