APEXPROOT=../../../../../
APE=$APEXPROOT/sys/src/ape
</$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libbz2.a

OFILES=blocksort.$O\
      huffman.$O\
      crctable.$O\
      randtable.$O\
      compress.$O\
      decompress.$O\
      bzlib.$O

HFILES=\
	$APEXPROOT/sys/include/ape/bzlib.h\

<$APEXPROOT/sys/src/cmd/mksyslib

BZSOURCE=../../../external/bzip2

CC=pcc
CFLAGS=-c -I$BZSOURCE -D_POSIX_SOURCE

%.$O: $BZSOURCE/%.c
	$CC $CFLAGS $BZSOURCE/$stem.c
