APEXPROOT=../../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
#	/*wchar*/\
	fwide.$O\
	mbrlen.$O\
	mbrtowc.$O\
	mbsinit.$O\
	mbsrtowcs.$O\
	wcrtomb.$O\
	wcsrtombs.$O\
	wcswidth.$O\
	wctrans.$O\
	wctype.$O\
	wcwidth.$O\

HFILES=\
	$APEXPROOT/sys/include/ape/utf.h\

UPDATE=\
	mkfile\
	${OFILES:%.$O=%.c}\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=-c -D_POSIX_SOURCE -D_PLAN9_SOURCE -D_BSD_EXTENSION
