</$objtype/mkfile
DIRS=doc libfl flex 

all:V:
	for (i in $DIRS)
		@{ cd $i; mk }

install:V:
	for (i in $DIRS)
		@{ cd $i; mk $target }
	cp FlexLexer.h /sys/include/ape/

clean:V:
	for (i in $DIRS)
		@{ cd $i; mk $target }

nuke:V:
	for (i in $DIRS)
		@{ cd $i; mk $target }
	rm -f /sys/include/ape/FlexLexer.h

