</$objtype/mkfile
DIRS=doc libfl flex 
APEXPROOT=../../../../..

all:V:
	for (i in $DIRS)
		@{ cd $i; mk }

install:V:
	for (i in $DIRS)
		@{ cd $i; mk $target }
	cp FlexLexer.h $APEXPROOT/sys/include/ape/

clean:V:
	for (i in $DIRS)
		@{ cd $i; mk $target }

nuke:V:
	for (i in $DIRS)
		@{ cd $i; mk $target }
	rm -f $APEXPROOT/sys/include/ape/FlexLexer.h

