APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libap.a
OFILES=\
	ctermid.$O\
	getopt.$O\
	getprogname.$O\
	getrusage.$O\
	ioctl.$O\
	pty.$O\
	setprogname.$O\
	syslog.$O\
	uname.$O\
# musl\
	a64l.$O\
	realpath.$O\
	getopt_long.$O\
	nftw.$O\
# fts-standalone\
	fts.$O\


<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=-c -I$APEXPROOT/sys/include/ape -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE -I../plan9 -I../include
