</$objtype/mkfile
APEXPROOT=../../../../../..
GSEDSRC=../../../../external/gsed

default:VQ:
	;

install:VQ:
	;

clean:VQ:
	;

nuke:VQ:
	rm -f $APEXPROOT/sys/man/1/sed
	;

install:V:
	cp $GSEDSRC/doc/sed.1 $APEXPROOT/sys/man/1/sed

