</$objtype/mkfile
APEXPROOT=../../../../..
TARG=m4
LIB=libgnu.a$O\
	$APEXPROOT/$objtype/lib/ape/libintl.a\
	$APEXPROOT/$objtype/lib/ape/libxml2.a

OFILES=\
	#src\
		builtin.$O\
		debug.$O\
		eval.$O\
		format.$O\
		freeze.$O\
		input.$O\
		m4.$O\
		macro.$O\
		output.$O\
		path.$O\
		symtab.$O

#minimized gnulib
LIB_OBJS= \
	asyncsafe-spin.$O\
	basename-lgpl.$O\
	c-stack.$O\
	c-strcasecmp.$O\
	canonicalize.$O\
	canonicalize-lgpl.$O\
	clean-temp.$O\
	clean-temp-simple.$O\
	close-stream.$O\
	closein.$O\
	closeout.$O\
	concat-filename.$O\
	dup-safer.$O\
	dup-safer-flag.$O\
	error.$O\
	execute.$O\
	fatal-signal.$O\
	fd-safer.$O\
	fd-safer-flag.$O\
	filenamecat.$O\
	filenamecat-lgpl.$O\
	file-set.$O\
	findprog-in.$O\
	fopen-safer.$O\
 	freadahead.$O\
	fseterr.$O\
	gl_avltree_oset.$O\
	gl_linked_list.$O\
	gl_linkedhash_list.$O\
	hash.$O\
	hashcode-named-file.$O\
	hashcode-string1.$O\
	hashcode-string2.$O\
	hashkey-string.$O\
	mbslen.$O\
	mbsstr.$O\
	memchr2.$O\
	mempcpy.$O\
	mkstemp-safer.$O\
	malloca.$O\
	next-prime.$O\
	pipe2-safer.$O\
	progname.$O\
	propername.$O\
	quotearg.$O\
	regex.$O\
	secure_getenv.$O\
	spawn-pipe.$O\
	strnlen1.$O\
	strsignal.$O\
	strstr.$O\
	tempname.$O\
	tmpdir.$O\
	trim.$O\
	vaszprintf.$O\
	version-etc.$O\
	version-etc-fsf.$O\
	vfzprintf.$O\
	vzprintf.$O\
	wait-process.$O\
	xasprintf.$O\
	xmalloca.$O\
	xmemdup0.$O\
	xprintf.$O\
	xvasprintf.$O\
# lib/malloc \
	dynarray_at_failure.$O\
	dynarray_emplace_enlarge.$O\
	dynarray_finalize.$O\
	dynarray_resize.$O\
# lib/glthread \
	lock.$O\
	spin.$O\



BIN=$APEXPROOT/$objtype/bin/ape
HFILES=config.h

<$APEXPROOT/sys/src/cmd/mkone

M4SRC=../../../external/m4

#during building from scratch, the new pcc is not picked up and compilation
#fails on include_next
CC=$APEXPROOT/$objtype/bin/pcc

UNRPL= -Drpl_readlink=readlink -Drpl_lseek=lseek -Drpl_posix_spawn_file_actions_addopen=posix_spawn_file_actions_addopen\
		-Drpl_open=open -Drpl_free=free -Drpl_malloc=malloc -Drpl_strtod=strtod -Drpl_realloc=realloc -Drpl_calloc=calloc\
		-Drpl_fcntl=fcntl -Drpl_mkstemp=mkstemp


CFLAGS=-c -B -I. -I$M4SRC -I$M4SRC/src  -I$M4SRC/lib -DHAVE_CONFIG_H\
	-D__USE_GNU -D_REGEX_LARGE_OFFSETS -D_POSIX_SOURCE -DO_BINARY=0\
	-D_BSD_EXTENSION -DSETLOCALE_NULL_MAX=(256+1) $UNRPL

%.$O: $M4SRC/src/%.c
	$CC $CFLAGS $M4SRC/src/$stem.c

%.$O: $M4SRC/lib/%.c
	$CC $CFLAGS $M4SRC/lib/$stem.c

%.$O: $M4SRC/lib/malloc/%.c
	$CC $CFLAGS $M4SRC/lib/malloc/$stem.c

%.$O: $M4SRC/lib/glthread/%.c
	$CC $CFLAGS $M4SRC/lib/glthread/$stem.c

libgnu.a$O: $LIB_OBJS
	ar vu libgnu.a$O $LIB_OBJS

CLEANFILES=libgnu.a$O



