APEXPROOT=../../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
	_pthread.$O\
	cond_broadcast.$O\
	cond_destroy.$O\
	cond_init.$O\
	cond_signal.$O\
	cond_wait.$O\
	pthread_create.$O\
	pthread_equal.$O\
	pthread_exit.$O\
	pthread_getspecific.$O\
	pthread_join.$O\
	pthread_key_create.$O\
	pthread_key_delete.$O\
	mutexattr_destroy.$O\
	mutexattr_init.$O\
	mutexattr_settype.$O\
	mutex_destroy.$O\
	mutex_init.$O\
	mutex_lock.$O\
	mutex_trylock.$O\
	mutex_unlock.$O\
	pthread_once.$O\
	pthread_self.$O\
	setcancelstate.$O\
	pthread_setspecific.$O\
	pthread_sigmask.$O\
# hacks \
	semaphore.$O\
	pthread_ext.$O\


HFILES=../include/lib.h

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=-c -D_POSIX_SOURCE -FTVw -D_SUSV2_SOURCE -D_PLAN9_SOURCE -I../include
