</$objtype/mkfile

TARG=6l
OFILES=\
	asm.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	list.$O\
	enam.$O\
	compat.$O\

HFILES=\
	l.h\
	../6c/6.out.h\

APEXPROOT=../../../..
BIN=$APEXPROOT/$objtype/bin
CFILES=${OFILES:%.$O=%.c}
CFILES=${CFILES:enam.c=../6c/enam.c}
UPDATE=\
	mkfile\
	$HFILES\
	$CFILES\
	${TARG:%=/386/bin/%}\

<$APEXPROOT/sys/src/cmd/mkone

../6c/enam.c: ../6c/6.out.h
	@ { cd ../6c; mk enam.c }

enam.$O:	../6c/enam.c
	$CC $CFLAGS ../6c/enam.c

compat.$O:	../cc/compat
