APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libtcl.a

UNIX_OBJS = tclUnixChan.$O tclUnixEvent.$O\
#	tclUnixFCmd.$O \
	tclUnixFile.$O tclUnixPipe.$O tclUnixSock.$O \
	tclUnixTime.$O tclUnixInit.$O tclUnixThrd.$O \
	tclUnixCompat.$O

TOMMATH_OBJS = bn_s_mp_reverse.$O bn_s_mp_mul_digs_fast.$O \
	bn_s_mp_sqr_fast.$O bn_mp_add.$O bn_mp_and.$O \
	bn_mp_add_d.$O bn_mp_clamp.$O bn_mp_clear.$O bn_mp_clear_multi.$O \
	bn_mp_cmp.$O bn_mp_cmp_d.$O bn_mp_cmp_mag.$O \
	bn_mp_cnt_lsb.$O bn_mp_copy.$O \
	bn_mp_count_bits.$O bn_mp_div.$O bn_mp_div_d.$O bn_mp_div_2.$O \
	bn_mp_div_2d.$O bn_s_mp_div_3.$O bn_mp_exch.$O bn_mp_expt_n.$O \
	bn_mp_get_mag_u64.$O \
	bn_mp_grow.$O bn_mp_init.$O \
	bn_mp_init_copy.$O bn_mp_init_multi.$O bn_mp_init_set.$O \
	bn_mp_init_size.$O bn_s_mp_karatsuba_mul.$O \
	bn_mp_init_i64.$O bn_mp_init_u64.$O \
	bn_s_mp_karatsuba_sqr.$O bn_s_mp_balance_mul.$O \
	bn_mp_lshd.$O bn_mp_mod.$O bn_mp_mod_2d.$O bn_mp_mul.$O bn_mp_mul_2.$O \
	bn_mp_mul_2d.$O bn_mp_mul_d.$O bn_mp_neg.$O bn_mp_or.$O bn_mp_pack.$O \
	bn_mp_pack_count.$O bn_mp_radix_size.$O bn_mp_radix_smap.$O  \
	bn_mp_set_i64.$O bn_mp_read_radix.$O bn_mp_rshd.$O \
	bn_mp_set_u64.$O bn_mp_shrink.$O \
	bn_mp_sqr.$O bn_mp_sqrt.$O bn_mp_sub.$O bn_mp_sub_d.$O \
	bn_mp_signed_rsh.$O \
	bn_mp_to_ubin.$O bn_mp_unpack.$O \
	bn_s_mp_toom_mul.$O bn_s_mp_toom_sqr.$O bn_mp_to_radix.$O \
	bn_mp_ubin_size.$O bn_mp_xor.$O bn_mp_zero.$O bn_s_mp_add.$O \
	bn_s_mp_mul_digs.$O bn_s_mp_sqr.$O bn_s_mp_sub.$O

GENERIC_OBJS = regcomp.$O regexec.$O regfree.$O regerror.$O tclAlloc.$O \
	tclArithSeries.$O tclAssembly.$O tclAsync.$O tclBasic.$O tclBinary.$O \
	tclCkalloc.$O tclClock.$O tclClockFmt.$O tclCmdAH.$O tclCmdIL.$O tclCmdMZ.$O \
	tclCompCmds.$O tclCompCmdsGR.$O tclCompCmdsSZ.$O tclCompExpr.$O \
	tclCompile.$O tclConfig.$O tclDate.$O tclDictObj.$O tclDisassemble.$O \
	tclEncoding.$O tclEnsemble.$O \
	tclEnv.$O tclEvent.$O tclExecute.$O tclFCmd.$O tclFileName.$O tclGet.$O \
	tclHash.$O tclHistory.$O \
	tclIcu.$O tclIndexObj.$O tclInterp.$O tclIO.$O tclIOCmd.$O \
	tclIORChan.$O tclIORTrans.$O tclIOGT.$O tclIOSock.$O tclIOUtil.$O \
	tclLink.$O tclListObj.$O \
	tclLiteral.$O tclLoad.$O tclMain.$O tclNamesp.$O tclNotify.$O \
	tclObj.$O tclOptimize.$O tclPanic.$O tclParse.$O tclPathObj.$O tclPipe.$O \
	tclPkg.$O tclPkgConfig.$O tclPosixStr.$O \
	tclPreserve.$O tclProc.$O tclProcess.$O tclRegexp.$O \
	tclResolve.$O tclResult.$O tclScan.$O tclStringObj.$O tclStrIdxTree.$O \
	tclStrToD.$O tclThread.$O \
	tclThreadAlloc.$O tclThreadJoin.$O tclThreadStorage.$O tclStubInit.$O \
	tclTimer.$O tclTrace.$O tclUtf.$O tclUtil.$O tclVar.$O tclZlib.$O \
	tclTomMathInterface.$O tclZipfs.$O

OO_OBJS = tclOO.$O tclOOBasic.$O tclOOCall.$O tclOODefineCmds.$O tclOOInfo.$O \
	tclOOMethod.$O tclOOProp.$O tclOOStubInit.$O

NOTIFY_OBJS = tclEpollNotfy.$O tclKqueueNotfy.$O tclSelectNotfy.$O


OFILES=\
# plan9 \
	plan9compat.$O\
# unix \
	$UNIX_OBJS\
	$NOTIFY_OBJS\
# generic \
	$GENERIC_OBJS\
	$OO_OBJS\
# libtommath \
	$TOMMATH_OBJS


TCLSRC=$APEXPROOT/sys/src/external/tcl

HFILES=\
	$TCLSRC/plan9/tclConfig.h\

<$APEXPROOT/sys/src/cmd/mklib

CFLAGS=-FVp -c -I$TCLSRC/plan9 -I$TCLSRC/generic -I$TCLSRC/unix\
	-I$TCLSRC/libtommath -DHAVE_TCL_CONFIG_H -DPLAN9 -DMODULE_SCOPE=/**/

%.$O: $TCLSRC/plan9/%.c
	$CC $CFLAGS $TCLSRC/plan9/$stem.c

%.$O: $TCLSRC/libtommath/%.c
	$CC $CFLAGS $TCLSRC/libtommath/$stem.c

%.$O: $TCLSRC/generic/%.c
	$CC $CFLAGS $TCLSRC/generic/$stem.c

%.$O: $TCLSRC/unix/%.c
	$CC $CFLAGS $TCLSRC/unix/$stem.c


