APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

TCLSRC=$APEXPROOT/sys/src/external/tcl

BIN=$APEXPROOT/$objtype/bin
TARG=tclsh

OFILES=tclAppInit.$O
LIB=$APEXPROOT/$objtype/lib/ape/libtcl.a $APEXPROOT/$objtype/lib/ape/libz.a

<$APEXPROOT/sys/src/cmd/mkone

CFLAGS=-FVp -c -I$TCLSRC/plan9 -I$TCLSRC/generic\
	-I$TCLSRC/unix -I$TCLSRC/libtommath\
	-DHAVE_TCL_CONFIG_H -DPLAN9

$O.out: $OFILES $LIB
	$LD $LDFLAGS -o $target $prereq

tclAppInit.$O: $TCLSRC/unix/tclAppInit.c
	$CC $CFLAGS $TCLSRC/unix/tclAppInit.c

