APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

TCLSRC=$APEXPROOT/sys/src/external/tcl

BIN=$APEXPROOT/$objtype/bin
TARG=tclsh
CLEANFILES=tcltest

OFILES=tclAppInit.$O
LIB=$APEXPROOT/$objtype/lib/ape/libtcl.a $APEXPROOT/$objtype/lib/ape/libz.a

<$APEXPROOT/sys/src/cmd/mkone

CFLAGS=-Fp -c -I$APEXPROOT/sys/src/ape/lib/tcl\
	-I$TCLSRC/plan9 -I$TCLSRC/generic\
	-I$TCLSRC/unix -I$TCLSRC/libtommath\
	-DHAVE_TCL_CONFIG_H -DPLAN9

$O.out: $OFILES $LIB
	$LD $LDFLAGS -o $target $prereq

tclAppInit.$O: $TCLSRC/unix/tclAppInit.c
	$CC $CFLAGS $TCLSRC/unix/tclAppInit.c

# Test-only interpreter, analogous to Tcl's upstream tcltest target.  It is
# deliberately not installed as /bin/tclsh; run it from this directory as
# ./tcltest <...>/tests/all.tcl.
TESTOFILES=tclTestInit.$O tclTest.$O tclTestObj.$O tclTestProcBodyObj.$O \
	tclMutexTest.$O tclThreadTest.$O tclUnixTest.$O tclTestABSList.$O \
	tclStubLib.$O tclStubCall.$O tclStubLibTbl.$O \
	tclTomMathStubLib.$O tclOOStubLib.$O

tcltest:V: $TESTOFILES $LIB
	$LD $LDFLAGS -o $target $prereq

tclTestInit.$O: $TCLSRC/unix/tclAppInit.c
	$CC $CFLAGS -DTCL_TEST -o $target $TCLSRC/unix/tclAppInit.c

tclTest.$O: $TCLSRC/generic/tclTest.c
	$CC $CFLAGS $TCLSRC/generic/tclTest.c

tclTestObj.$O: $TCLSRC/generic/tclTestObj.c
	$CC $CFLAGS $TCLSRC/generic/tclTestObj.c

tclTestProcBodyObj.$O: $TCLSRC/generic/tclTestProcBodyObj.c
	$CC $CFLAGS $TCLSRC/generic/tclTestProcBodyObj.c

tclMutexTest.$O: $TCLSRC/generic/tclMutexTest.c
	$CC $CFLAGS $TCLSRC/generic/tclMutexTest.c

tclThreadTest.$O: $TCLSRC/generic/tclThreadTest.c
	$CC $CFLAGS $TCLSRC/generic/tclThreadTest.c

tclUnixTest.$O: $TCLSRC/unix/tclUnixTest.c
	$CC $CFLAGS $TCLSRC/unix/tclUnixTest.c

tclTestABSList.$O: $TCLSRC/generic/tclTestABSList.c
	$CC $CFLAGS $TCLSRC/generic/tclTestABSList.c

# Tcl's test extension is built against the public, internal, TclOO, and
# TomMath stub interfaces.  The release libtcl.a does not carry these client
# side stub objects, so link them into the test interpreter only.
tclStubLib.$O: $TCLSRC/generic/tclStubLib.c
	$CC $CFLAGS -DSTATIC_BUILD $TCLSRC/generic/tclStubLib.c

tclStubCall.$O: $TCLSRC/generic/tclStubCall.c
	$CC $CFLAGS -DSTATIC_BUILD $TCLSRC/generic/tclStubCall.c

tclStubLibTbl.$O: $TCLSRC/generic/tclStubLibTbl.c
	$CC $CFLAGS -DSTATIC_BUILD $TCLSRC/generic/tclStubLibTbl.c

tclTomMathStubLib.$O: $TCLSRC/generic/tclTomMathStubLib.c
	$CC $CFLAGS $TCLSRC/generic/tclTomMathStubLib.c

tclOOStubLib.$O: $TCLSRC/generic/tclOOStubLib.c
	$CC $CFLAGS $TCLSRC/generic/tclOOStubLib.c
