APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config


TARG=expr
OFILES=y.tab.$O
YFILES=expr.y
HFILES=regexp.h

BIN=$APEXPROOT/$objtype/bin/ape

<$APEXPROOT/sys/src/cmd/mkone

YFLAGS=-S
CFLAGS=-B -c

install:V:

