APEXPROOT=../../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a

OFILES=\
	hsearch.$O\
	insque.$O\
	lsearch.$O\
	tdelete.$O\
	tdestroy.$O\
	tfind.$O\
	tsearch.$O\
	twalk.$O

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -c -I../include -D_POSIX_SOURCE
