APEXPROOT=../../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config
LIB=$APEXPROOT/$objtype/lib/ape/libap.a
OFILES=\
	_seek.$O\
	cycles.$O\
	getfcr.$O\
	lock.$O\
	main9.$O\
	main9p.$O\
	memmove.$O\
	memset.$O\
	notetramp.$O\
	setjmp.$O\
	tas.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=-c -D_POSIX_SOURCE -D_PLAN9_SOURCE

