BUILTINS=
</$objtype/mkfile
<../c++mkfile

$O.out:	patch.$O
	$LD $prereq

install:V:	$O.out
	mv $O.out /$objtype/bin/c++/patch

installall:V:
	for(objtype in $CPUS)
		mk install

%.$O:	%.c
	$CC -w $stem.c

clean:V:
	rm -f *.[$OS] [$OS].out y.tab.?

nuke:V: clean
