BUILTINS=
</$objtype/mkfile
<../c++mkfile

$O.out:	ccrun.$O
	$LD ccrun.$O

install:V:	ccrun.install
	for(i in $CCS)
		cp script /$objtype/bin/c++/$i

ccrun.install:V:	$O.out
	mv $O.out /$objtype/bin/c++/ccrun

installall:V:
	for(objtype in $CPUS)
		mk install

%.$O:	%.c
	$CC -w $stem.c

clean:V:
	rm -f *.[$OS] [$OS].out y.tab.?

nuke:V: clean
