APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
</$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libhistory.a
BIN=$APEXPROOT/$objtype/bin/ape

HISTOBJ=history.$O\
	histexpand.$O\
	histfile.$O\
	histsearch.$O\
	shell.$O\
	mbutil.$O\

OFILES=\
	$HISTOBJ\
	xmalloc.$O\
	xfree.$O\


<$APEXPROOT/sys/src/cmd/mksyslib

RLSRC=../../../external/readline

#during building from scratch, the new pcc is not picked up and compilation
#fails on include_next
CC=$APEXPROOT/$objtype/bin/pcc

CFLAGS=-c -DHAVE_CONFIG_H -D_POSIX_SOURCE -DHAVE_CURSES_H -DHAVE_STDLIB_H\
	-I$RLSRC -DRL_LIBRARY_VERSION='"8.3"' -DBRACKETED_PASTE_DEFAULT=1

%.$O: $RLSRC/%.c
	$CC $CFLAGS $RLSRC/$stem.c





