APEXPROOT=../../../../..
APE=$APEXPROOT/sys/src/ape
<$APE/config

CXXSRC=$APEXPROOT/sys/src/external/cfront-C4

BIN=$APEXPROOT/$objtype/bin/ape
TARG= cfront munch ns_strip c++filt ptcomp ptlink szal

CFILES=\
	Bits.$O\
	_stdio.$O\
	alloc.$O\
	block.$O\
	cfront_stubs.$O\
	dcl.$O\
	dcl2.$O\
	dcl3.$O\
	dcl4.$O\
	del.$O\
	discrim.$O\
	error.$O\
	expand.$O\
	expr.$O\
	expr2.$O\
	expr3.$O\
	find.$O\
	hash.$O\
	lalex.$O\
	lex.$O\
	main.$O\
	norm.$O\
	norm2.$O\
	print.$O\
	print2.$O\
	repr.$O\
	simpl.$O\
	simpl2.$O\
	size.$O\
	table.$O\
	template.$O\
	tree_copy.$O\
	tree_walk.$O\
	typ.$O\
	typ2.$O\
	pregen-y.tab.$O\

<$APEXPROOT/sys/src/cmd/mkmany

# -D__cfront_have_bool: APExp pcc has bool/true/false as C23 keywords,
# so suppress cfront's own "enum bool { false, true }" in template.h.
CFLAGS= -c -B -D_POSIX_SOURCE -D_BSD_EXTENSION -D__cfront_have_bool -I$CXXSRC/src

%.$O: $CXXSRC/src/%.c
	$CC $CFLAGS $prereq -o $target

%.$O: $CXXSRC/tools/demangler/%.c
	$CC $CFLAGS -I$CXXSRC/demangler -DDEM_MAIN $prereq -o $target

munch-%.$O: $CXXSRC/tools/munch/%.c
	$CC $CFLAGS $prereq -o $target

%.$O: $CXXSRC/tools/szal/%.c
	$CC $CFLAGS $prereq -o $target

%.$O: $CXXSRC/tools/pt/%.c
	$CC $CFLAGS -I$CXXSRC/demangler $prereq -o $target

pt-dem.$O: $CXXSRC/tools/demangler/dem.c
	$CC $CFLAGS -I$CXXSRC/demangler $prereq -o $target

$O.cfront: $CFILES
	$LD $prereq -o $target

$O.ns_strip: ns_strip.$O
	$LD $prereq -o $target

$O.c++filt: dem.$O
	$LD $prereq -o $target

$O.munch: munch-munch.$O munch-dtors.$O munch-_main.$O munch-init.$O
	$LD $prereq -o $target

$O.ptcomp: ptcomp.$O ptutil.$O
	$LD $prereq -o $target

$O.ptlink: ptlink.$O ptutil.$O pt-dem.$O
	$LD $prereq -o $target

$O.szal: szal.$O
	$LD $prereq -o $target
	mkdir -p $APEXPROOT/sys/lib/c++
	./$O.szal | sort > $APEXPROOT/sys/lib/c++/$O.sz

RCBIN=$APEXPROOT/rc/bin/ape

# Install the c++ rc driver script alongside the compiled tools.
# mkmany's install:V: handles the binaries in TARG; this rule appends
# to it (multiple V: rules for the same target all execute in Plan9 mk).
# install installall:V:
#	mkdir -p $RCBIN
#	cp $CXXSRC/tools/CC-driver/c++ $RCBIN/c++










