</$objtype/mkfile

TARG=9a
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	../9c/9.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

APEXPROOT=../../../..
BIN=$APEXPROOT/$objtype/bin
< $APEXPROOT/sys/src/cmd/mkone
YFLAGS=-D1 -d

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat
