</$objtype/mkfile

TARG=ql
OFILES=\
	asm.$O\
	asmout.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	cnam.$O\
	sched.$O\
	compat.$O\

HFILES=\
	l.h\
	../qc/q.out.h\
	../cc/compat.h\

APEXPROOT=../../../..
BIN=$APEXPROOT/$objtype/bin
<$APEXPROOT/sys/src/cmd/mkone

../qc/enam.c: ../qc/q.out.h
	@ { cd ../qc; mk enam.c }

enam.$O:	../qc/enam.c
	$CC $CFLAGS ../qc/enam.c

cnam.c:	l.h mkcname
	rc ./mkcname

compat.$O:	../cc/compat
