APEXPROOT=../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

DIRS=gen math fenv plan9 posix stdio syscall

default:V:	all

install all:V:
	for(i in $DIRS $objtype)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}

installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install


clean nuke:V:
	for(i in $DIRS $CPUS)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}
