APEXPROOT=../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

# libap and libbsd have been merged
# source code re-organized like the musl src directory

DIRS=\
#	complex\
	conf\
	ctype\
	dirent\
	env\
	errno\
	exit\
	fcntl\
	fenv\
	fmt\
	legacy\
	locale\
	malloc\
	math\
	misc\
	multibyte\
	network\
	passwd\
	plan9\
	prng\
	process\
	regex\
	search\
	select\
	signal\
	stat\
	stdio\
	stdlib\
	string\
	syscall\
	temp\
	termios\
	thread\
	time\
	unistd\
	wchar


default:V:	all

install all:V:
	for(i in $DIRS)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}
	for(j in $objtype)@{
		echo arch/$j
		cd arch/$j
		mk $MKFLAGS $target
	}


installall:V:
	for(objtype in $CPUS)@{
		mk $MKFLAGS install
	}


clean nuke:V:
	for(i in $DIRS)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}
