/*
 * The C locale character table. THE OFFSETS IN THE COMMENTS BELOW ARE
 * OCTAL: the row marked 10 starts at 8, and the row marked 40 starts
 * at 32, which is SPACE.
 *
 * TAB (octal 11) LACKED _ISblank, AND IT COST A LONG HUNT.
 * C99 7.4.1.3: isblank() is true for exactly space and horizontal tab
 * in the "C" locale. This table gave it to space alone, so
 * isblank('\t') answered FALSE for every program in the tree.
 *
 * What that cost: bash's `syntax.c' is GENERATED by its own
 * `mksyntax', whose addblanks() is literally
 *
 *	"... the default blank characters will be space and tab."
 *	if (isblank (uc)) lsyntax[uc] |= CBLANK;
 *
 * so the table generated here gave TAB `CSHBRK' with no `CBLANK'.
 * bash's `shellblank()' reads CBLANK and `shellbreak()' reads CSHBRK,
 * so a tab was NOT whitespace to skip but WAS a word delimiter:
 * read_token handed the tab to read_token_word, which ungot it and
 * returned a zero-length WORD, and the parser appended that empty
 * word and asked for another token -- for ever, at one WORD_LIST per
 * turn. ~17 million allocations and `Killed: Insufficient physical
 * memory' on any script with a TAB-INDENTED line.
 *
 * *One missing flag on one table entry, and the symptom was an
 * out-of-memory kill in a different program.*
 */
#include <ctype.h>

unsigned char	_ctype[] =
{
/* 	0			1			2			3  */
/* 	4			5			6			7  */

/*  0*/	_IScntrl,		_IScntrl,		_IScntrl,		_IScntrl,
	_IScntrl,		_IScntrl,		_IScntrl,		_IScntrl,
/* 10*/	_IScntrl,		_ISspace|_IScntrl|_ISblank,	_ISspace|_IScntrl,	_ISspace|_IScntrl,
	_ISspace|_IScntrl,	_ISspace|_IScntrl,	_IScntrl,		_IScntrl,
/* 20*/	_IScntrl,		_IScntrl,		_IScntrl,		_IScntrl,
	_IScntrl,		_IScntrl,		_IScntrl,		_IScntrl,
/* 30*/	_IScntrl,		_IScntrl,		_IScntrl,		_IScntrl,
	_IScntrl,		_IScntrl,		_IScntrl,		_IScntrl,
/* 40*/	_ISspace|_ISblank,	_ISpunct,		_ISpunct,		_ISpunct,
	_ISpunct,		_ISpunct,		_ISpunct,		_ISpunct,
/* 50*/	_ISpunct,		_ISpunct,		_ISpunct,		_ISpunct,
	_ISpunct,		_ISpunct,		_ISpunct,		_ISpunct,
/* 60*/	_ISdigit|_ISxdigit,	_ISdigit|_ISxdigit,	_ISdigit|_ISxdigit,	_ISdigit|_ISxdigit,
	_ISdigit|_ISxdigit,	_ISdigit|_ISxdigit,	_ISdigit|_ISxdigit,	_ISdigit|_ISxdigit,
/* 70*/	_ISdigit|_ISxdigit,	_ISdigit|_ISxdigit,	_ISpunct,		_ISpunct,
	_ISpunct,		_ISpunct,		_ISpunct,		_ISpunct,
/*100*/	_ISpunct,		_ISupper|_ISxdigit,	_ISupper|_ISxdigit,	_ISupper|_ISxdigit,
	_ISupper|_ISxdigit,	_ISupper|_ISxdigit,	_ISupper|_ISxdigit,	_ISupper,
/*110*/	_ISupper,		_ISupper,		_ISupper,		_ISupper,
	_ISupper,		_ISupper,		_ISupper,		_ISupper,
/*120*/	_ISupper,		_ISupper,		_ISupper,		_ISupper,
	_ISupper,		_ISupper,		_ISupper,		_ISupper,
/*130*/	_ISupper,		_ISupper,		_ISupper,		_ISpunct,
	_ISpunct,		_ISpunct,		_ISpunct,		_ISpunct,
/*140*/	_ISpunct,		_ISlower|_ISxdigit,	_ISlower|_ISxdigit,	_ISlower|_ISxdigit,
	_ISlower|_ISxdigit,	_ISlower|_ISxdigit,	_ISlower|_ISxdigit,	_ISlower,
/*150*/	_ISlower,		_ISlower,		_ISlower,		_ISlower,
	_ISlower,		_ISlower,		_ISlower,		_ISlower,
/*160*/	_ISlower,		_ISlower,		_ISlower,		_ISlower,
	_ISlower,		_ISlower,		_ISlower,		_ISlower,
/*170*/	_ISlower,		_ISlower,		_ISlower,		_ISpunct,
	_ISpunct,		_ISpunct,		_ISpunct,		_IScntrl,
/*200*/	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0,
	 0,	 0,	 0,	 0,	 0,	 0,	 0,	 0
};
