</$objtype/mkfile
APEXPROOT=../../../../../..
TARG=sed
OFILES=	compile.$O\
		execute.$O\
		fmt.$O\
		mbcs.$O\
		regexp.$O\
		sed.$O\
		utils.$O

LIB=../lib/libsed.a$O $APEXPROOT/$objtype/lib/ape/libutf.a
BIN=$APEXPROOT/$objtype/bin/ape

<$APEXPROOT/sys/src/cmd/mkone

GSEDSRC=../../../../external/gsed

CC=pcc
LD=pcc
CFLAGS=-c -I.. -I$GSEDSRC -I$GSEDSRC/sed -I$GSEDSRC/lib -B -DHAVE_CONFIG_H

%.$O: $GSEDSRC/sed/%.c
	$CC $CFLAGS $GSEDSRC/sed/$stem.c
