</$objtype/mkfile
APEXPROOT=../../../../../..
T=2
OFILES=\
	2c_vla.$O\
	cgen.$O\
	reg.$O\
	txt.$O\
	peep.$O\
	swt.$O\
	sgen.$O\
	list.$O\
	enam.$O\
	mul.$O\

<../mkcompiler

%.$O: $APEXPROOT/sys/src/cmd/2c/%.c
	$CC $CFLAGS $prereq

