APEXPROOT=../../../../../
APE=$APEXPROOT/sys/src/ape
<$APE/config

LIB=$APEXPROOT/$objtype/lib/ape/libl.a
OFILES=allprint.$O\
	main.$O\
	reject.$O\
	yyless.$O\
	yywrap.$O\

<$APEXPROOT/sys/src/cmd/mksyslib

CFLAGS=-c -D_RESEARCH_SOURCE
